<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<title>微信开放平台授权页面</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="keywords" content="财猪">
	<meta name="description" content="财猪">
	<meta name="viewport"
	      content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="format-detection" content="telephone=no">
</head>
<body>
</body>
<script>
	var url = '<?php echo $this->url?>';
	window.location.href = url;
</script>
</html>
