
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="member_add_form" method="post" action="">
            <table class='form_table'>                
                <tr>
                    <th width="15%">邮箱：</th>
                    <td width="85%"><input class="easyui-validatebox" type="text"  data-options="required:true" size="50" name="email"/></td>
                </tr>
                 <tr>
                    <th>密码：</th>
                    <td>
                        <input class="easyui-validatebox" type="password" data-options="required:true" size="50" name="password" />
                    </td>
                </tr>              
                <tr>
                    <td colspan='2' class='footbar'>
                    </td>
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="member_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="member_add_form_close">关闭</a>
        </div>
    </div>
</div>