
              
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <!--<span >h5:</span>
        <span ><input type = "text" value="<?php echo $this->h5Url ?>" size="65" id="member_h5" /></span>
        <span ><input type="button"  value = "复制" class="copy_btn"  data-value-id="member_h5"/></span>-->
    </div>
    <div style="padding:10px 0 10px 30px;align:center;">
        <span >schema:</span>
        <span ><input type = "text" value ="<?php echo $this->schemaUrl; ?>" size="65" id="member_schema"/> </span>
        <span ><input type="button"  value = "复制" class="copy_btn" data-value-id="member_schema" /> </span>
    </div>
</div>