<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="lesson_add_form" method="post" action="" enctype="multipart/form-data">
            <table class='form_table' cellspacing="15">
                <tr>
                    <th width="20%">课程标题：</th>
                    <td width="80%"><input class="easyui-validatebox" type="text" name="LessonTitle" value = "" data-options="required:true" size="50" /></td>
                </tr>
                <tr>
                    <th width="20%">课堂模块：</th>
                    <td width="80%">
                        <select name="ModuleID">
                            <?php foreach ($this->moduleList as $item):?>
                                <option value="<?php echo $item['ModuleID']?>"><?php echo $item['ModuleName'];?></option>
                            <?php endforeach;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>课程图片：</th>
                    <td>
                        <input name = "image"  type="file"/>
                    </td>
                </tr>
                <tr>
                    <th>课程类型：</th>
                    <td>
                        <select name="LessonType">
                            <option value="1">图文</option>
                            <option value="2">视频</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>状态：</th>
                    <td>
                        <input name="Status" type="radio" value="0" />隐藏
                        <input name="Status" checked="checked" type="radio" value="1" />显示
                    </td>
                </tr>
                <tr>
                    <th>课程简介：</th>
                    <td>
                        <textarea rows="5" cols="50" name="LessonDes"></textarea>          
                    </td>    
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="lesson_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="lesson_add_form_close">关闭</a>
        </div>
    </div>
</div>