<!--内容部分-->
<table id="best_title_list"></table>
<div id="best_title_list_toolbar">
	<a href="javascript:void(0);" class="easyui-linkbutton" iconCls="icon-add" plain="true"
	   onclick="best_titleObj.addHandler();">添加</a>
	<a id="refresh" class="easyui-linkbutton" iconCls="icon-reload" plain="true">刷新</a>
	名称：
	<input type="text" value="" name="Name" size="20"/> &nbsp;&nbsp;

	创建时间：
	<input class="easyui-datetimebox" type="text" name="Start_CreateTime" value="" data-options=""/>
	至&nbsp;<input class="easyui-datetimebox" type="text" name="End_CreateTime" value="" data-options=""/>
	<a class="easyui-linkbutton" iconCls="icon-search" id="search">搜索</a>
</div>

<div id="best_title_view"></div>
<div id="img_dialog" class="easyui-dialog" title="img" closed="true" data-options="resizable:'true'"
     style="width: 400px;height: 400px;">
</div>

<script type="text/javascript">
	var best_titleObj = {
		//数据加载url
		'loadUrl': '<?php echo $this->url(array('controller'=>'best-title','action'=>'list'));?>',
		'addUrl': '<?php echo $this->url(array('controller'=>'best-title','action'=>'add'));?>',
		'editUrl': '<?php echo $this->url(array('controller'=>'best-title','action'=>'edit'));?>',

		//审核专栏
		'add_feature': {
			'width': 400,
			'height': 200,
			'title': '新增'
		},

		'edit_feature': {
			'width': 400,
			'height': 200,
			'title': '编辑'
		},

		//加载数据
		'showData': function () {
			var _THIS_ = this;
			_THIS_.container.datagrid({

				//是否条纹显示
				striped: true,
				//加载提示信息
				loadMsg: '正在加载...',
				//列是否自适应
				//fitbest_titles:true,
				rownumbers: true,
				fit: true,
				//是否单行选择
				singleSelect: true,

				idField: 'TID',

				url: _THIS_.loadUrl,

				toolbar: '#best_title_list_toolbar',

				//设置列
				columns: [[
					{field: 'Name', title: '名称', width: 60},
					{field: 'CreateTime', title: '创建时间', width: 150},
					{
						field: 'opt', title: '操作', align: 'center', formatter: function (value, rec, index) {
						var c = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" ' +
							'onclick="' + _THIS_.selfName + '.editHandler(\'?TID=' + rec.TID + '\')">';
						c += '<span class="l-btn-left">编辑</span></a>';

						return c;
					}
					}

				]],

				//分页信息
				pagination: true,
				//pagePosition:'both',
				pageList: [20, 50, 100, 150, 200],
				pageSize: 50
			});

		}
	};
</script>
<script type="text/javascript">
	var __CONTROLLER__ = '<?php echo $this->CONTROLLER;?>';
</script>
<script type="text/javascript" src="/static/js/admin/content.js"></script>
<script type="text/javascript">
	best_titleObj = contentCommon(best_titleObj, __CONTROLLER__);
</script>
