
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="reply_check_form" method="post" action="" enctype="multipart/form-data">
            <table class='form_table'>                
                 <tr>
                    <td width="40%">    
                        <select name="Status">
                            <?php if($this->status==0):?>
                                <option value="1">通过</option>
                            <?php elseif($this->status==1):?>
                                <option value="0">隐藏</option>                         
                            <?php endif;?>
                        </select>
                    </td>
                </tr>
                <tr <?php if($this->status == 0):?> style="display:none" <?php endif;?>>
                    <td colspan="2" valign="center"><br/>理由：&nbsp;&nbsp;<textarea name = "remark"　cols="20" rows="3"></textarea></td>
                </tr>   
                <tr>
                    <td class='footbar'>
                    <input type="hidden" name="replyID" value="<?php echo $this->reply_id;?>"/>
                    </td>
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px ">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="reply_check_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="reply_check_form_close">关闭</a>
        </div>
    </div>
</div>