
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="view_check_form" method="post" action="" enctype="multipart/form-data">
            <table class='form_table'>                
                 <tr>
                    <td width="40%">    
                        <select name="checkStatus">
                            <?php if($this->status==0):?>
                                <option value="1">通过</option>
                                <option value="2">隐藏</option>
                            <?php elseif($this->status==1):?>
                                <option value="3">屏蔽</option>
                                <option value="2">隐藏</option>
                            <?php elseif($this->status==2):?>
                                <option value="1">通过</option>
                            <?php elseif($this->status==3 || $this->status==4):?>
                                <option value="1">取消屏蔽</option>
                                <option value="2">隐藏</option>
                            <?php endif;?>
                        </select>
                    </td>
                    <td width="60%" id="hide" <?php if(in_array($this->status, array(0,2))):?> style="display:none" <?php endif;?>>
                            <input name="remind" type="checkbox" checked="checked" value="1" />通知举报人与发布人
                            <br/>
                            <?php if($this->status == 1):?>
                                <input name="forbid" type="checkbox"  value="1"  />是否禁言
                            <?php endif;?>
                    </td>
                </tr>
                <tr id = "reason" <?php if(in_array($this->status, array(0,2))):?> style="display:none" <?php endif;?>>
                    <td colspan="2" valign="center"><br/>理由：&nbsp;&nbsp;<textarea name = "Reason"　cols="20" rows="3"></textarea></td>
                </tr>
               
                <tr>
                    <td colspan='2' class='footbar'>
                    <input type="hidden" name="viewID" value="<?php echo $this->view_id;?>"/>
                    </td>
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px ">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="view_check_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="view_check_form_close">关闭</a>
        </div>
    </div>
</div>
<script type="text/javascript">
    var original_status = 0;
    <?php if(in_array($this->status, array(3,4))):?>
        original_status = 1;
    <?php endif;?>
    $("select[name='checkStatus']").change(function(){
        var status = $(this).val();
        if(status ==3 || (status==1 && original_status)){
            document.getElementById("hide").style.display = '';
        }else{
            document.getElementById("hide").style.display = 'none';
        }
        if(status==1){
            document.getElementById("reason").style.display = 'none';
        }else{
            document.getElementById("reason").style.display = '';
        }
    });

</script>