#!/bin/sh
#describe:vsftpd sh
#author:wujp

#source funtions
#"." include file
. /etc/init.d/functions

#source network
. /etc/sysconfig/network

#check network is up
[ $NETWORKING == "no" ] && echo 'NETWORKING IS NO' && exit 0

#path init
vsftpd=/usr/local/sbin/vsftpd
pid=/data0/pids/vsftpd.pid

#return init
RETVAL=0
prog="vsftpd"


check_nginx(){
       ps -ef |grep -v grep |grep vsftpd >/dev/null

       if [ $? == 0 ];then    #等号两边要有空格
          echo "$prog already runing"
          return 0
       fi

    return 1
}

start(){
   check_nginx

   if [ ! $? == 0 ];then
     echo "starting $prog"
     $vsftpd &
     RETVAL=$?
   fi

}

stop(){
   echo "stoping $prog"
   killproc vsftpd
   RETVAL=$?
   [ $RETVAL == 0 ] && rm -rf $nginxpid
}

#start
case "$1" in
   start)
       start
       ;;
   stop)
       stop
       ;;
   restart)
       stop
       start
       ;;
   status)
       status $prog
       RETVAL=$?
       ;;
   *)
       echo "Usage:$0 {start|stop|restart|status}"
       RETVAL=1
esac

exit $RETVAL