
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
    
        <form id="lesson_module_edit_form" method="post" enctype="multipart/form-data">
           <table class='form_table' cellspacing="15">                
                <tr>
                    <th width="20%">模块名称：</th>
                    <td width="80%"><input class="easyui-validatebox" type="text" name="ModuleName" value = "<?php echo $this->lessonModuleInfo['ModuleName'];?>" data-options="required:true" size="50" /></td>
                </tr>
                <tr>
                    <th>背景图片：</th>
                    <td>
                        <image width="50" height="50" src="<?php echo $this->lessonModuleInfo['ModulePic'].'?imageView2/0/w/200/h/200' ?>" />
                        <input name = "image"  type="file"/>
                    </td>
                </tr> 
                 <tr>
                    <th>状态：</th>
                    <td>
                        <input name="CheckStatus" <?php if($this->lessonModuleInfo['Status']==0):?> checked="checked" <?php endif;?> type="radio" value="0" />隐藏
                        <input name="CheckStatus" <?php if($this->lessonModuleInfo['Status']==1):?> checked="checked" <?php endif;?> type="radio" value="1" />显示
                    </td>
                </tr>
                <tr>
                    <th>位置：</th>
                    <td>
                           <input type="text" name="DisOrder"  value="<?php echo $this->lessonModuleInfo['DisOrder']?>" />               
                    </td>    
                </tr>
              
                <tr>
                    <td colspan='2' class='footbar'>
                        <input type="hidden" name="ModuleID" value="<?php echo $this->lessonModuleInfo['ModuleID']?>" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    
    <div style="text-align:center;padding:5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" id="lesson_module_edit_form_save">保存</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" id="lesson_module_edit_form_close">关闭</a>
    </div>
     
</div>