
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
    
        <form id="vote_view_edit_form" method="post" >
           <table class='form_table'>
                <tr>
                    <th width="25%">选择期数：</th>
                    <td width="75%">
                        <select name="PeriodID">
                            <?php foreach ($this->periodInfo as $item):?>
                                <option value="<?php echo $item['PeriodID'];?>" <?php if($item['PeriodID']==$this->voteViewInfo['PeriodID']){ echo "selected ='selected'";} ?>><?php echo $item['PeriodName'];?></option>
                            <?php endforeach;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th >观点ID：</th>
                    <td> <input type="text" name="ViewID"  size="50" value="<?php echo $this->voteViewInfo['ViewID'];?>" ></input></td>
                </tr>
                <tr>
                    <th>观点类型：</th>
                    <td>
                        <input  type="radio" name="ViewType" value="1" <?php if($this->voteViewInfo['ViewType']==1):?>checked="checked" <?php endif;?> />投票观点&nbsp;&nbsp;
                        <input  type="radio" name="ViewType" value="2" <?php if($this->voteViewInfo['ViewType']==2):?> checked="checked" <?php endif;?> />热门观点
                    </td>
                </tr>

                <!--<tr id = 'hot' <?php if($this->voteViewInfo['ViewType']==1):?> style="display:none" <?php endif;?>>
                    <th>热门观点url：</th>
                    <td>
                        <input  type="text" name="Url" size="50" value="<?php echo $this->voteViewInfo['Url'];?>" ></input>
                    </td>
                </tr>-->

                <tr>
                    <th>状态：</th>
                    <td>
                        <input  type="radio" name="Status" value="0" <?php if($this->voteViewInfo['Status']==0):?>checked="checked" <?php endif;?>>无效</input>
                        <input  type="radio" name="Status" value="1" <?php if($this->voteViewInfo['Status']==1):?>checked="checked" <?php endif;?>>有效</input>
                    </td>
                </tr>
                <tr>
                    <td colspan='2' class='footbar'>
                        <input type="hidden" name="VoteViewListID" value="<?php echo $this->voteViewInfo['VoteViewListID']?>" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    
    <div style="text-align:center;padding:5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" id="vote_view_edit_form_save">保存</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" id="vote_view_edit_form_close">关闭</a>
    </div>
     
</div>

<!--<script type="text/javascript">

    $("input[name='ViewType']").change(function(){
        var type = $(this).val();
        if(type==2){
            document.getElementById("hot").style.display = '';
        }else{
            document.getElementById("hot").style.display = 'none';
        }
    });

</script>-->