<div class="easyui-panel" style="border:0px;">
    <div style="align:center;">
        <form id="wordsAds_add_form" method="post" action="<?php echo $this->url(array('controller'=>'words-ads','action'=>'add'));?>" enctype="multipart/form-data">
            <table class='form_table'>                
                <tr>
                    <th width="20%">广告标题：</th>
                    <td width="80%">
                        <input class="easyui-validatebox" type="text" name="Title" data-options="required:true" size="35" value="<?php if(isset($this->info['Title'])) echo $this->info['Title'];?>" />
                    </td>
                </tr> 
                <tr>
                    <th>广告链接：</th>
                    <td width="80%">
                        <input class="easyui-validatebox" type="text" name="Link" data-options="required:true" size="35" value="<?php if(isset($this->info['Link'])) echo $this->info['Link'];?>" />
                    </td>
                </tr>         
                <tr>
                    <th>所属模块：</th>
                    <td>
                        <select name="ShowType">
                        <?php 
                        if(isset($this->showType) && $this->showType) {
                            foreach ($this->showType as $k => $v) {
                                if( isset($this->info['ShowType']) ) {?>
                                    <option value="<?php echo $k;?>" <?php if($this->info['ModuleType'] == $k) echo 'selected="selected"';?> ><?php echo $v;?></option>&nbsp;&nbsp;&nbsp;
                                <?php } else {?>
                                    <option value="<?php echo $k;?>" <?php if(1 == $k) echo 'selected="selected"';?> ><?php echo $v;?></op>&nbsp;&nbsp;&nbsp;
                                <?php }
                             }
                        }?>
                        </select>
                        <?php if( isset($this->info['AID']) ) {?>
                            <input type="hidden" value="<?php echo $this->info['AID'];?>" name="id" />
                        <?php }?>
                    </td>
                </tr>
                 <tr>
                    <th>排序：</th>
                    <td width="80%">
                        <input class="easyui-validatebox" type="text" name="Sort" data-options="required:false" size="5" value="<?php if(isset($this->info['Sort'])) echo $this->info['Sort'];?>" />
                    </td>
                </tr>  
            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="wordsAds_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="wordsAds_add_form_close">关闭</a>
        </div>
    </div>
</div>