 <?php if( isset($this->error) && $this->error ):?>
 	<?php echo $this->error;?>
 <?php else:?>
 <table style="width:210px;border-collapse:collapse;">
 	<thead>
 		<tr>
	 		<th></th>
 			<th>群成员</th>
 			<th>群昵称</th>
 		</tr>
 	</thead>
 	<tbody>
	 	<?php
	 	if( isset($this->members) && $this->members ) {
	 		foreach ($this->members as $k => $member) {?>
		<tr style="border: 1px solid #f0f0f0;">
			<td><?php echo ($this->pageIndex - 1) * $this->pageSize + $k + 1;?></td>
			<td><?php echo $member['MemberID'];?></td>
			<td><?php echo $member['NickName'];?></td>
		</tr>
	 	<?php }
		}?>
 	</tbody>
 </table>
 <p align="center"><?php if($this->pageIndex > 1):?><a href="javascript:groupObj.showMembers(<?php echo $this->groupID;?>, <?php echo $this->pageIndex-1;?>)">上一页</a><?php endif;?><?php if($this->total > ($this->pageIndex * $this->pageSize)):?> | <a href="javascript:groupObj.showMembers(<?php echo $this->groupID;?>, <?php echo $this->pageIndex+1;?>)">下一页</a><?php endif;?></p>
 <?php endif;?>