<!DOCTYPE HTML>
<html lang="zh-CN">
<title>财猪客户端下载</title>
<meta charset="utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
<meta name="keywords" content="财猪" >
<meta name="description" content="财猪下载客户端" >
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" >
<meta name="apple-mobile-web-app-capable" content="yes" >
<meta name="apple-mobile-web-app-status-bar-style" content="black" >
<meta content="telephone=no" name="format-detection" >
<link rel="stylesheet" href="/static/css/api/m-main.css" >

<script src="/static/js/web/zepto.min.js"></script>
</head>
<style>
    html, body{
        height: 100%;
    }
    body{
        min-width: 320px;
        max-width: 640px;
        margin: 0 auto;
        font: 14px/1.5 helvetica,arial,"Microsoft YaHei","微软雅黑",sans-serif;
        background: #ff8505;
    }
    .main{
        margin: 10px 0 0;
        text-align: center;
        background: url('/static/imgs/web/main.png') no-repeat  center center;
        background-size: contain;

    }
    .main img{
        height: 100%;
    }
    .do{
        text-align: center;
    }
    .do span{
        display: inline-block;
        padding: 15px 30px;
        line-height: 20px;
        color: #8d3722;
        background: #ffde03;
        border-radius: 30px;
        font-size: 18px;
        margin: 0 8px;

        -webkit-transition: all .2s linear;
        transition: all .2s linear;
    }
    .do span:active{
        background: #C2583C;
        color: #fff;
    }
    .do li{
        margin: 20px 0 0;
    }



    /* 整理结构 来点自适应 */

    .box{
        height: 100%;
        overflow: hidden;
        display: -webkit-box;
        display: -moz-box;
        display: box;
        -webkit-box-orient: vertical;
        -moz-box-orient: vertical;
        box-orient: vertical;
    }
    .main{
        -webkit-box-flex: 1;
        -moz-box-flex: 1;
        -ms-box-flex: 1;
        box-flex: 1;
    }
    .text{
        height: 100px;
        text-align: center;
        padding: 20px 0 0;
    }
    .text img{
        max-width: 250px;
    }
    .do{
        height: 100px;
    }

    #os-android{
        background: url('/static/imgs/web/android.png') no-repeat center 20px;
    }
    #os-ios{
        background: url('/static/imgs/web/ios.png') no-repeat center 20px;
    }
    #os-android, #os-ios{
        position: fixed;
        top: -2px;
        left: 0;
        background-size: 80% auto;
        background-color: rgba(10, 10, 10, .6);
        padding: 0 0 3px;
    }

    .os-close{
        position: absolute;
        right: -18px;
        top: -16px;
        width: 55px;
        height: 55px;
        font-size: 24px;
        color: #fff;
        background: rgba(255, 255, 255, .2);
        border-radius: 30px;
        line-height: 68px;
        text-indent: 12px;
    }
</style>

<body>

<section class="box">
    <figure class="text"><img src="/static/imgs/web/text.png" alt="文字" ></figure>
    <figure class="main"><!--<img src="/static/imgs/web/main.png" alt="主图" >--></figure>

    <ul class="do">
        <li>
            <span id="caizhu-down" data-android="http://img.caizhu.com/caizhu1.1.2.apk" data-ios="">立即下载财猪</span>
        </li>
    </ul>

</section>


<div id="os-android" class="hide"><span class="os-close">X</span></div>
<div id="os-ios" class="hide"><span class="os-close">X</span></div>

<script>

    $(function(){

        function detect(ua, platform) {
            var os = {}, browser = {},
                    webkit = ua.match(/Web[kK]it[\/]{0,1}([\d.]+)/),
                    android = ua.match(/(Android);?[\s\/]+([\d.]+)?/),
                    osx = !!ua.match(/\(Macintosh\; Intel /),
                    ipad = ua.match(/(iPad).*OS\s([\d_]+)/),
                    ipod = ua.match(/(iPod)(.*OS\s([\d_]+))?/),
                    iphone = !ipad && ua.match(/(iPhone\sOS)\s([\d_]+)/),
                    webos = ua.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),
                    win = /Win\d{2}|Windows/.test(platform),
                    wp = ua.match(/Windows Phone ([\d.]+)/),
                    touchpad = webos && ua.match(/TouchPad/),
                    kindle = ua.match(/Kindle\/([\d.]+)/),
                    silk = ua.match(/Silk\/([\d._]+)/),
                    blackberry = ua.match(/(BlackBerry).*Version\/([\d.]+)/),
                    bb10 = ua.match(/(BB10).*Version\/([\d.]+)/),
                    rimtabletos = ua.match(/(RIM\sTablet\sOS)\s([\d.]+)/),
                    playbook = ua.match(/PlayBook/),
                    chrome = ua.match(/Chrome\/([\d.]+)/) || ua.match(/CriOS\/([\d.]+)/),
                    firefox = ua.match(/Firefox\/([\d.]+)/),
                    firefoxos = ua.match(/\((?:Mobile|Tablet); rv:([\d.]+)\).*Firefox\/[\d.]+/),
                    ie = ua.match(/MSIE\s([\d.]+)/) || ua.match(/Trident\/[\d](?=[^\?]+).*rv:([0-9.].)/),
                    webview = !chrome && ua.match(/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/),
                    safari = webview || ua.match(/Version\/([\d.]+)([^S](Safari)|[^M]*(Mobile)[^S]*(Safari))/);


            if (browser.webkit = !!webkit) browser.version = webkit[1]

            if (android) os.android = true, os.version = android[2]
            if (iphone && !ipod) os.ios = os.iphone = true, os.version = iphone[2].replace(/_/g, '.')
            if (ipad) os.ios = os.ipad = true, os.version = ipad[2].replace(/_/g, '.')
            if (ipod) os.ios = os.ipod = true, os.version = ipod[3] ? ipod[3].replace(/_/g, '.') : null
            if (wp) os.wp = true, os.version = wp[1]
            if (webos) os.webos = true, os.version = webos[2]
            if (touchpad) os.touchpad = true
            if (blackberry) os.blackberry = true, os.version = blackberry[2]
            if (bb10) os.bb10 = true, os.version = bb10[2]
            if (rimtabletos) os.rimtabletos = true, os.version = rimtabletos[2]
            if (playbook) browser.playbook = true
            if (kindle) os.kindle = true, os.version = kindle[1]
            if (silk) browser.silk = true, browser.version = silk[1]
            if (!silk && os.android && ua.match(/Kindle Fire/)) browser.silk = true
            if (chrome) browser.chrome = true, browser.version = chrome[1]
            if (firefox) browser.firefox = true, browser.version = firefox[1]
            if (firefoxos) os.firefoxos = true, os.version = firefoxos[1]
            if (ie) browser.ie = true, browser.version = ie[1]
            if (safari && (osx || os.ios || win)) {
                browser.safari = true
                if (!os.ios) browser.version = safari[1]
            }
            if (webview) browser.webview = true

            os.tablet = !!(ipad || playbook || (android && !ua.match(/Mobile/)) ||
            (firefox && ua.match(/Tablet/)) || (ie && !ua.match(/Phone/) && ua.match(/Touch/)))
            os.phone = !!(!os.tablet && !os.ipod && (android || iphone || webos || blackberry || bb10 ||
            (chrome && ua.match(/Android/)) || (chrome && ua.match(/CriOS\/([\d.]+)/)) ||
            (firefox && ua.match(/Mobile/)) || (ie && ua.match(/Touch/))));
            return {
                os: os,
                browser: browser
            }
        }

        var wxFlag=function(){
            var ua = navigator.userAgent.toLowerCase();
            if(ua.match(/MicroMessenger/i)=="micromessenger") {
                return true;
            } else {
                return false;
            }
        }();

        var info=detect(navigator.userAgent, navigator.platform);


        var hide = 'hide',
            $osAnd = $('#os-android'), $osIos = $('#os-ios'),
            $caizhuDown = $('#caizhu-down');

        var winW = window.innerWidth, winH = window.innerHeight;
                $osAnd.css({'width': winW, 'height': winH});
                $osIos.css({'width': winW, 'height': winH});

        $('.os-close').click(function(){
            $(this).parent().addClass(hide);
        })

        if(wxFlag){
           $caizhuDown.click(function(){
                if(info.os.android){
                    $osAnd.removeClass(hide)
                }else if(info.os.ios){
                    //$osIos.removeClass(hide);
                    location.href = $caizhuDown.data('ios')
                }
            });
        }else{

            var $this = $(this), url;

            if(info.os.android){
                url = $caizhuDown.data('android');
            }else if(info.os.ios){
                url = $caizhuDown.data('ios');
            }else{
                url = $caizhuDown.data('android');        // 默认给android下载包
            }

            $caizhuDown.click(function(){
                location.href = url;
            })
        }

    });

</script>

<script src="https://fe.caizhu.com/public/js/apph5-action.js"></script>
</body>
</html>
