<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
<title>请在财猪扫一扫</title>
<meta charset="utf-8" >
<meta name="keywords" content="请在财猪扫一扫" >
<meta name="description" content="请在财猪扫一扫" >
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" >
<meta content="telephone=no" name="format-detection" >
<!--<link rel="stylesheet" href="/static/css/api/m-main.css" >-->

<style>
    *{margin: 0; padding: 0; list-style: normal; }

    p{font-size: 16px; font-weight: bold; color: #555; text-align: center; margin: 50px 0 0;}

</style>

</head>
<body>

<p class="content-empty">
    请使用财猪里的扫一扫！
</p>

<script src="https://fe.caizhu.com/public/js/apph5-action.js"></script>
</body>
</html>