<table id="adsBar_list"></table>
<div id="adsBar_list_toolbar"></div>
<div id="adsBar_view_window"></div>
<div id="adsBar_list_searcher_container">
<form action="" id="adsBar_search_form">
    <a href="javascript:void(0);" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="adsBarObj.editHandler();">添加</a> 
    <a href="javascript:void(0);" class="easyui-linkbutton" iconCls="icon-reload" plain="true" onclick="adsBarObj.containerObj.edatagrid('reload');">刷新</a>
    创建时间：<input class="easyui-datetimebox" type="text" name="start_date" value="" data-options=""></input>
    至&nbsp;<input class="easyui-datetimebox" type="text" name="end_date" value="" data-options="" />
    &nbsp;
    广告位编号：&nbsp;<input type="text" name="BarNum" value="" size="5" /> 
    展现类型：
    <select name="ShowType">
        <option value="">---</option>
        <?php if(isset($this->showType) && $this->showType) {
                foreach ($this->showType as $key => $value) {
                echo '<option value="'.$key.'">'.$value.'</option>';
            }
        }?>
    </select>
    <a href="javascript:void(0);" class="easyui-linkbutton" onclick="javascript:toSearchAdsBarList()" iconCls="icon-search">搜索</a>
</form>
</div>
<div id="adsBar_add_window"></div>
<script type="text/javascript">
        $("#adsBar_list_searcher_container input[name]").keydown(function(event){
            if(event.keyCode == 13){
                toSearchAdsBarList();
            }    
        });
        
        $("#adsBar_list_searcher_container select[name]").change(function(){
            toSearchAdsBarList();
        });
        
        function toSearchAdsBarList() {
            adsBarObj.containerObj.datagrid('load', $('#adsBar_search_form').serializeObject());
        }

        var adsBarObj = {
            //数据加载url
            'loadUrl':'<?php echo $this->url(array('controller'=>'ads-bar','action'=>'list'));?>',
            'deleteUrl':'<?php echo $this->url(array('controller'=>'ads-bar','action'=>'remove'));?>',

            'containerObj':$("#adsBar_list"),
            'addWindowObj':$("#adsBar_add_window"),
            'selfName':'adsBarObj',

            'init':function(){
                this.showData();
            },

            //添加或修改话题
            'editHandler':function(id){
                    var _THIS_ = this;
                    if( id ) {
                        var href = '<?php echo $this->url(array('controller'=>'ads-bar','action'=>'add'));?>' + '?id=' + id;
                        var title = '编辑广告位';
                    } else {
                        var href = '<?php echo $this->url(array('controller'=>'ads-bar','action'=>'add'));?>';
                        var title = '添加广告位';
                    }
                    _THIS_.addWindowObj.window({
                        'href': href,
                        'width': 250,
                        'height': 160,
                        'modal': true,
                        'resizable': true,
                        'title': title,
                        'onLoad':function() {
                            $('#adsBar_add_form_save').on('click', function() {
                                $("#adsBar_add_form").submit();
                            });

                            $('#adsBar_add_form_close').on('click', function() {
                                _THIS_.addWindowObj.window('close');
                            });
                            
                            $("#adsBar_add_form").myForm(function(ret){
                                if(ret.flag > 0){
                                    _THIS_.addWindowObj.window('close');
                                    _THIS_.containerObj.datagrid('reload');
                                } else {
                                    $.messager.alert("提示信息", ret.msg, 'error');
                                }
                            });    
                        }
                    });
                },

            //删除
            'delHandler':function(id){
                            var _THIS_ = this;
                            $.messager.confirm('删除','确认要删除吗？', function(d){
                                if(d) {
                                    $.ajax({
                                            url:_THIS_.deleteUrl,
                                            type: "POST",
                                            data: {id:id},
                                            dataType: 'json',
                                            success: function(ret){
                                                if(ret.flag > 0) {
                                                    $.messager.alert("提示信息",'删除成功！','info');
                                                    _THIS_.containerObj.datagrid('reload');
                                                } else{
                                                    $.messager.alert("提示信息",ret.msg,'error');
                                                }
                                            }
                                    });
                                }
                            });
                        },

            //加载数据
            'showData':function(){
                var _THIS_ = this;
                _THIS_.containerObj.datagrid({
                        //是否条纹显示
                        striped:true,
                        //加载提示信息
                        loadMsg:'正在加载...',
                        //列是否自适应
                        //fitColumns:true,
                        rownumbers : true,
                        fit:true, 
                        //是否单行选择
                        singleSelect:true,
                        idField:'AdsID',
                        url:_THIS_.loadUrl,
                        toolbar: '#adsBar_list_toolbar',
            
                        //设置列   
                        columns:[[
                            {field:'AdsBarID',title:'广告位ID',width:80}, 
                            {field:'BarNum',title:'广告位',width:50}, 
                            {field:'AdsType',title:'广告类型',width:70,formatter:function(value,rec,index){
                                var type = '';
                                switch(value){
                                    case '1':
                                        type = '推广';
                                        break;
                                    case '2':
                                        type = '活动';
                                        break;
                                }
                                return type;
                            }

                            },  
                            {field:'ShowType',title:'展示类型',width:80, formatter: function(value, rec, index) {
                                var showType = {<?php if(isset($this->showType) && $this->showType) {
                                    foreach ($this->showType as $key => $value) {
                                        echo "\"{$key}\":\"{$value}\"";
                                        $arr = array_keys($this->showType);
                                        if( end($arr) !== $key ) {
                                            echo ',';
                                        }
                                    }
                                }
                                ?>}
                                if( typeof(showType[value]) != 'undefined' ) {
                                    return showType[value];
                                }
                                return value;
                            }},
                            {field:'CreateTime',title:'创建时间',width:150}, 
                            {field:'opt',title:'操作',align:'center',formatter:function(value,rec,index){
                                 var e = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" onclick="'+_THIS_.selfName+'.editHandler(\''+rec.AdsBarID+'\')">';
                                     e += '<span class="l-btn-left"><span class="l-btn-text icon-edit l-btn-icon-left">编辑</span></span></a>';
                                 var d = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-remove" onclick="'+_THIS_.selfName+'.delHandler(\''+rec.AdsBarID+'\')">';
                                     d += '<span class="l-btn-left"><span class="l-btn-text icon-remove l-btn-icon-left">删除</span></span></a>';
                                 return e+d;         
                               }
                            }

                        ]],

                        //分页信息
                        pagination:true,
                        // pagePosition:'both',
                        pageList:[20,50,100,150,200],
                        pageSize:50,
                    });

                $("#adsBar_list_toolbar").append($("#adsBar_list_searcher_container"));
            },    
    };
    adsBarObj.init();
</script>
