<!--内容部分-->
<table id="feature_group_list"></table>
<div id="feature_group_list_toolbar">
	<a id="add" class="easyui-linkbutton" iconCls="icon-add" plain="true">添加</a>
	<a id="refresh" class="easyui-linkbutton" iconCls="icon-reload" plain="true">刷新</a>
	名称：
	<input type="text" value="" name="Name" size="20"/> &nbsp;&nbsp;

	状态：
	<select name="Status">
		<option value="">所有</option>
		<option value="0">无效</option>
		<option value="1">有效</option>
	</select>&nbsp;&nbsp;
	创建时间：
	<input class="easyui-datetimebox" type="text" name="Start_CreateTime" value="" data-options=""/>
	至&nbsp;<input class="easyui-datetimebox" type="text" name="End_CreateTime" value="" data-options=""/>
	<a class="easyui-linkbutton" iconCls="icon-search" id="search">搜索</a>
</div>

<div id="feature_group_view"></div>
<div id="img_dialog" class="easyui-dialog" title="img" closed="true" data-options="resizable:'true'"
     style="width: 400px;height: 400px;">
</div>

<script type="text/javascript">
	var feature_groupObj = {
		//数据加载url
		'loadUrl': '<?php echo $this->url(array('controller'=>'feature-group','action'=>'list'));?>',
		'addUrl': '<?php echo $this->url(array('controller'=>'feature-group','action'=>'add'));?>',
		'editUrl': '<?php echo $this->url(array('controller'=>'feature-group','action'=>'edit'));?>',
		//审核专栏
		'add_feature': {
			'width': 400,
			'height': 200,
			'title': '新增功能组'
		},
		'edit_feature': {
			'width': 400,
			'height': 200,
			'title': '编辑功能组'
		},
		//加载数据
		'showData': function () {
			var _THIS_ = this;
			_THIS_.container.datagrid({

				//是否条纹显示
				striped: true,
				//加载提示信息
				loadMsg: '正在加载...',
				//列是否自适应
				//fitfeature_groups:true,
				rownumbers: true,
				fit: true,
				//是否单行选择
				singleSelect: true,

				idField: 'GID',

				url: _THIS_.loadUrl,

				toolbar: '#feature_group_list_toolbar',

				//设置列
				columns: [[
					{field: 'GID', title: '功能组ID', width: 40},
					{field: 'Name', title: '名称', width: 60},
					{
						field: 'Status', title: '状态', width: 70, formatter: function (value, rec, index) {
						var status = '';
						switch (value) {
							case '0':
								status = '无效';
								break;
							case '1':
								status = '有效';
								break;
						}
						return status;
					}
					},
					{field: 'CreateTime', title: '创建时间', width: 150},
					{
						field: 'opt', title: '操作', align: 'center', formatter: function (value, rec) {
						var c = "";
						c += '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" ' +
							'onclick="' + _THIS_.selfName + '.editHandler(\'?GID=' + rec.GID + '\')">';
						c += '<span class="l-btn-left"><span class="l-btn-text icon-edit l-btn-icon-left">编辑</span></span></a>';
						return c;

					}
					}

				]],

				//分页信息
				pagination: true,
				//pagePosition:'both',
				pageList: [20, 50, 100, 150, 200],
				pageSize: 50
			});

		}
	};
</script>
<script type="text/javascript">
	var __CONTROLLER__ = '<?php echo $this->CONTROLLER;?>';
</script>
<script type="text/javascript" src="/static/js/admin/content.js"></script>
<script type="text/javascript">
	feature_groupObj = contentCommon(feature_groupObj, __CONTROLLER__);
</script>