<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="gift_add_form" method="post" action="<?php echo $this->url(array('controller'=>'gift','action'=>'add'));?>" enctype="multipart/form-data">
            <table class='form_table'>   
                <tr>
                    <th>礼物名称:</th>
                    <td><input type="text" name="giftName" value="<?php if(isset($this->info['GiftName'])) echo $this->info['GiftName'];?>"></td>
                </tr>               
                <tr>
                    <th width="20%">礼物价格：</th>
                    <td width="80%">
                        <input class="easyui-validatebox" type="text" name="price"  size="50" value="<?php if(isset($this->info['Price'])) echo $this->info['Price'];?>" />
                    </td>
                </tr>
           
                 <tr>
                    <th>礼物单位：</th>
                    <td>
                        <input class="easyui-validatebox" type="text" name="Unit"  size="50" value="<?php if(isset($this->info['Unit'])) echo $this->info['Unit'];?>"/>
                    </td>
                </tr> 
                <tr>
                    <th>礼物icon：</th>
                    <td>
                        <input name="icon" type="file" />
                    </td>
                </tr> 
               <tr>
                    <th>礼物类型：</th>
                    <td>
                        <select name="giftType">
                        <?php if(isset($this->info['Type'])){?>
                       	<option  value="1" <?php if($this->info['Type']==1) echo "selected";?>>现金</option>
                      	<option  value="2" <?php if($this->info['Type']==2) echo "selected";?>>虚拟商品</option>
                      	<?php }else{?>
                      	<option  value="1" >现金</option>
                      	<option  value="2">虚拟商品</option>
                      	<?php }?>
                       </select>
                        <?php if( isset($this->info['GiftID']) ) {?>
                            <input type="hidden" value="<?php echo $this->info['GiftID'];?>" name="id" />
                        <?php }?>
                    </td>
                </tr>
                <tr>
                    <th>状态：</th>
                    <td>
                        <?php 
                        if(isset($this->status) && $this->status) {
                            foreach ($this->status as $k => $v) {
                                if( isset($this->info['Status']) )  {?>
                                    <label><input type="radio" value="<?php echo $k?>" name="Status" <?php if($this->info['Status'] == $k) echo 'checked="checked"';?> />&nbsp;<?php echo $v;?></label>&nbsp;&nbsp;&nbsp;
                                <?php } else {?>
                                    <label><input type="radio" value="<?php echo $k?>" name="Status" <?php if(1 == $k) echo 'checked="checked"';?> />&nbsp;<?php echo $v;?></label>&nbsp;&nbsp;&nbsp;
                               <?php }
                            }
                        }?>
                    </td>
                </tr>              
               
        
            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="gift_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="gift_add_form_close">关闭</a>
        </div>
    </div>
</div>
<script type="text/javascript">
//function DoCheck(){
    //alert('kitty');
   // alert($(this).attr("checked"));
    //alert($("#selectAllChannels").is(':checked'));
    // var ch=document.getElementsByName("displayArr");
    // if(document.getElementsByName("allChecked")[0].checked==true){
    //     for(var i=0;i<ch.length;i++){
    //         ch[i].checked=true;
    //     }
    // }else{
    //     for(var i=0;i<ch.length;i++){
    //         ch[i].checked=false;
    //     }
    // }
   //$(".displayArr").attr('checked',allSelected);
//}

</script>
