<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">

		<form id="feature_add_form" method="post" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<th width="20%">组名：</th>
					<td width="80%">
						<select name="GID">
							<?php foreach ($this->groups as $id => $name) { ?>
								<option
									value="<?php echo $id; ?>">
									<?php echo $name; ?>
								</option>
							<?php } ?>
						</select>
					</td>
				</tr>
				<tr>
					<th width="20%">名称：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="Name"
					                       value=""
					                       data-options="required:true"
					                       size="50"/></td>
				</tr>
				<tr>
					<th width="20%">控制器：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="Controller"
					                       value=""
					                       data-options="required:true"
					                       size="50"/></td>
				</tr>
				<tr>
					<th width="20%">方法：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="Action"
					                       value=""
					                       data-options="required:true"
					                       size="50"/></td>
				</tr>
				<tr>
					<th>状态：</th>
					<td>
						<select name="Status">
							<option
								value="1">
								有效
							</option>
							<option
								value="0">
								无效
							</option>
						</select>
					</td>
				</tr>
			</table>
		</form>
	</div>

	<div style="text-align:center;padding:5px">
		<a href="javascript:void(0)" class="easyui-linkbutton" id="feature_add_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="feature_add_form_close">关闭</a>
	</div>

</div>