<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">

		<form id="force_activity_add_form" method="post" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<th width="20%">活动图片：</th>
					<td width="80%">
						<input name = "image"  type="file"/>
					</td>
				</tr>
				<tr>
					<th >活动名称：</th>
					<td >
						<input type="text" name="ActivityName" class="easyui-validatebox" data-options="required:true" size="50" />
					</td>
				</tr>
				<tr>
					<th >活动链接</th>
					<td >
						<input type="text" name="ActivityLink" class="easyui-validatebox" data-options="required:true" size="50" />
					</td>
				</tr>
				<tr>
					<th >次数/每天</th>
					<td >
						<input type="number" name="CountPerDay" value="0" size="25"/>
					</td>
				</tr>				<tr>
					<th >开始时间</th>
					<td >
						<input type="text" name="StartTime" class="easyui-datetimebox"  size="25" />
					</td>
				</tr>				<tr>
					<th >结束时间</th>
					<td >
						<input type="text" name="EndTime" class="easyui-datetimebox" size="25" />
					</td>
				</tr>							
			</table>
		</form>
	</div>

	<div style="text-align:center;padding:5px">
		<a href="javascript:void(0)" class="easyui-linkbutton" id="force_activity_add_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="force_activity_add_form_close">关闭</a>
	</div>

</div>