
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="focus_add_form" method="post" action="" enctype="multipart/form-data">
            <table class='form_table'>                
                <tr>
                    <th width="20%">标签：</th>
                    <td width="80%">
                        <input class="easyui-validatebox" type="text" name="FocusName" data-options="required:true" size="50" />
                    </td>
                </tr>
                <tr>
                    <th>标签类型：</th>
                    <td>
                        <input  type="checkbox" name="focusType[]" value = "IsBeforeRegisterFocus" /> 注册前关注点&nbsp;&nbsp;&nbsp;&nbsp;
                        <input  type="checkbox" name="focusType[]" value = "IsRegistedFocus" /> 注册后关注点&nbsp;&nbsp;&nbsp;&nbsp;
                        <input  type="checkbox" name="focusType[]" value = "IsGroupFocus" /> 群标签&nbsp;&nbsp;&nbsp;&nbsp;
                        <input  type="checkbox" name="focusType[]" value = "IsTopicFocus" /> 话题标签
                    </td>
                </tr>
                <tr>
                    <th>图片：</th>
                    <td>
                        <input name="image"  type="file"/>
                    </td>
                </tr>               
                <tr>
                    <th>所属频道：</th>
                    <td>
                        <?php 
                        if(isset($this->channels) && $this->channels) {
                            foreach ($this->channels as $item) {?>
                                <label><input type="checkbox" value="<?php echo $item['ChannelID'];?>" name="ChannelID[]" />&nbsp;<?php echo $item['ChannelName'];?></label>&nbsp;&nbsp;&nbsp;
                            <?php }
                        }?>
                    </td>
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="focus_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="focus_add_form_close">关闭</a>
        </div>
    </div>
</div>