<table id="focus_list"></table>
<div id="focus_list_toolbar"></div>
<div id="focus_view_window"></div>
<div id="focus_list_searcher_container">
    <a href="javascript:void(0);" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="focusObj.addHandler();">添加</a> 
    <a href="javascript:void(0);" class="easyui-linkbutton" iconCls="icon-reload" plain="true" onclick="focusObj.containerObj.edatagrid('reload');">刷新</a> 
   关注点：<input type="text" name="FocusName" />

    创建时间：
    <input class="easyui-datetimebox" type="text" name="start_date" value="" data-options=""></input>
    至&nbsp;<input class="easyui-datetimebox" type="text" name="end_date" value="" data-options=""></input>   
    <a href="javascript:void(0);" class="easyui-linkbutton" onclick="javascript:toSearchFocusList()" iconCls="icon-search">搜索</a>
</div>
<div id="focus_add_window"></div>
<div id="focus_edit_window"></div>

<script type="text/javascript">
    $("#focus_list_searcher_container input[name]").keydown(function(event){
        if(event.keyCode == 13){
            toSearchFocusList();
        }    
    });
    
    $("#focus_list_searcher_container select[name]").change(function(){
        toSearchFocusList();
    });
    
    function toSearchFocusList(flag)
    {
        var FocusName       = $("#focus_list_searcher_container input[name='FocusName']").val();
        var start_date      = $("#focus_list_searcher_container input[name='start_date']").val();
        var end_date        = $("#focus_list_searcher_container input[name='end_date']").val();
        
        focusObj.containerObj.datagrid('load', {
            FocusName:FocusName,
            start_date:start_date,
            end_date:end_date
        });
    }

var focusObj = {
        //数据加载url
        'loadUrl':'<?php echo $this->url(array('controller'=>'focus','action'=>'list'));?>',
        'addUrl':'<?php echo $this->url(array('controller'=>'focus','action'=>'add'));?>',
        'editUrl':'<?php echo $this->url(array('controller'=>'focus','action'=>'edit'));?>',
        'deleteUrl':'<?php echo $this->url(array('controller'=>'focus','action'=>'remove'));?>',

        'containerObj':$("#focus_list"),
        'addWindowObj':$("#focus_add_window"),
        'editWindowObj':$("#focus_edit_window"),
        
        'selfName':'focusObj',

        'init':function(){
            this.showData();
        },

        //添加话题
        addHandler:function(){
            var _THIS_ = this;
            _THIS_.addWindowObj.window({
                'href':_THIS_.addUrl,
                'width':500,
                'height':250,
                'modal':true,
                'resizable':false,
                'title':'添加',
                'onClose':function(){
                    _THIS_.addWindowObj.window('destroy');
                },
                'onLoad':function(){
                    $('#focus_add_form_save').on('click', function(){
                         $("#focus_add_form").attr('action',_THIS_.addUrl).submit();
                    });

                    $('#focus_add_form_close').on('click', function(){
                        _THIS_.addWindowObj.window('destroy');
                    });
                    $("#focus_add_form").myForm(function(ret){
                        if(ret.flag == 1){
                             _THIS_.addWindowObj.window('destroy');
                            _THIS_.containerObj.datagrid('reload');
                        } else{
                            $.messager.alert("提示信息",ret.msg,'error');
                        }
                    });
                    
                }
            });
        },

        //修改话题
        'editHandler':function(id){
                var _THIS_ = this;
                _THIS_.editWindowObj.window({
                        'href':_THIS_.editUrl+'?focus_id='+id,
                        'width':500,
                        'height':250,
                        'modal':true,
                        'resizable':true,
                        'title':'编辑会员',
                        'onLoad':function() {
                            $('#focus_edit_form_save').on('click', function() {
                                $("#focus_edit_form").attr('action',_THIS_.editUrl).submit();
                            });

                            $('#focus_edit_form_close').on('click', function() {
                                _THIS_.editWindowObj.window('close');
                            });
                            
                            $("#focus_edit_form").myForm(function(ret){
                                if(ret.flag){
                                    // $.messager.alert("提示信息",'修改成功！','info');
                                    _THIS_.editWindowObj.window('close');
                                    _THIS_.containerObj.datagrid('reload');
                                } else{
                                    $.messager.alert("提示信息",ret.msg,'error');
                                }
                            });    
                        }
                    });
            },

        //删除
        'delHandler':function(id){
                        var _THIS_ = this;
                        $.messager.confirm('删除','确认要删除吗？',function(d){
                            if(d){
                                $.ajax({
                                        url:_THIS_.deleteUrl,
                                        type:"POST",
                                        data:{focus_id:id},
                                        dataType:'json',
                                        success:function(ret){
                                            if(ret.flag > 0){
                                                $.messager.alert("提示信息",'删除成功！','info');
                                                _THIS_.containerObj.datagrid('reload');
                                            }else{
                                                $.messager.alert("提示信息",ret.msg,'error');
                                            }
                                        }
                                });
                            }
                        });
                    },

        //加载数据
        'showData':function(){
            var _THIS_ = this;
            _THIS_.containerObj.datagrid({
                    
                    //是否条纹显示
                    striped:true,
                    //加载提示信息
                    loadMsg:'正在加载...',
                    //列是否自适应
                    //fitColumns:true,
                    rownumbers : true,
                    fit:true, 
                    //是否单行选择
                    singleSelect:true,
    
                    idField:'FocusID',
    
                    url:_THIS_.loadUrl,

                    toolbar: '#focus_list_toolbar',
        
                    //设置列   
                    columns:[[
                        {field:'FocusID',title:'关注点ID',width:80}, 
                        {field:'FocusName',title:'标签名称',width:150}, 
                     
                        {field:'ChannelName',title:'所属频道',width:300},                       
                        {field:'FocusImg',title:'图片',width:200,formatter:function(value,rec,index){
                                return '<img src="'+value+'?imageView2/0/w/200/h/200"/>';
                            }
                        }, 
                        {field:'IsBeforeRegisterFocus',title:'注册前关注点',width:150,formatter:function(value,rec,index){
                                var status = '';
                                switch(value){
                                    case '0':
                                        status = '否';
                                        break;
                                    case '1':
                                        status = '是';
                                        break;
                                }
                                return status;
                            }
                        },
                        {field:'IsRegistedFocus',title:'注册后关注点',width:150,formatter:function(value,rec,index){
                                var status = '';
                                switch(value){
                                    case '0':
                                        status = '否';
                                        break;
                                    case '1':
                                        status = '是';
                                        break;
                                }
                                return status;
                            }
                        }, 
                        {field:'IsGroupFocus',title:'群标签',width:150,formatter:function(value,rec,index){
                                var status = '';
                                switch(value){
                                    case '0':
                                        status = '否';
                                        break;
                                    case '1':
                                        status = '是';
                                        break;
                                }
                                return status;
                            }
                        }, 
                        {field:'IsTopicFocus',title:'话题标签',width:150,formatter:function(value,rec,index){
                                var status = '';
                                switch(value){
                                    case '0':
                                        status = '否';
                                        break;
                                    case '1':
                                        status = '是';
                                        break;
                                }
                                return status;
                            }
                        }, 
                        {field:'CreateTime',title:'创建时间',width:150},  
                        {field:'opt',title:'操作',align:'center',formatter:function(value,rec,index){

                             var e = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" onclick="'+_THIS_.selfName+'.editHandler(\''+rec.FocusID+'\')">';
                                 e += '<span class="l-btn-left"><span class="l-btn-text icon-edit l-btn-icon-left">编辑</span></span></a>';
                             var d = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-remove" onclick="'+_THIS_.selfName+'.delHandler(\''+rec.FocusID+'\')">';
                                 d += '<span class="l-btn-left"><span class="l-btn-text icon-remove l-btn-icon-left">删除</span></span></a>';
                            return e;         
                           }
                        }

                    ]],

                    //分页信息
                    pagination:true,
                    //pagePosition:'both',
                    pageList:[20,50,100,150,200],
                    pageSize:50,
                });


            $("#focus_list_toolbar").append($("#focus_list_searcher_container"));
            },    
};
focusObj.init();
</script>
