<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
<title>财猪送流量</title>
<meta charset="utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
<meta name="keywords" content="" >
<meta name="description" content="" >
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" >
<meta name="apple-mobile-web-app-capable" content="yes" >
<meta name="apple-mobile-web-app-status-bar-style" content="black" >
<meta content="telephone=no" name="format-detection" >
<link rel="stylesheet" href="/static/css/hd/flow0916/style.css" >
<style>
body{background: #3F3CB1;}
</style>
</head>
<body>

<figure class="t-banner">
    <img src="/static/imgs/hd/flow0916/banner.png" alt="财猪送流量咯">
</figure>

<section class="flow-box">
    <div class="flow-one flow-ten">
        <img src="/static/imgs/hd/flow0916/result-nomore.png" alt="nomore" >
        <p>你怎么才来，100个流量名额被领取完了！</p>
    </div>
</section>



<script src="/static/js/web/zepto.min.js"></script>
<script>
$(function(){

    // active伪状态
    var acTime;
    $('.active').on('touchstart', function(){

        acTime = new Date();
        $(this).addClass('touch');

    }).on('touchend', function(){

        var $this = $(this), url;
        $this.removeClass('touch');
        if((new Date()) - acTime > 500){   // 触摸的时间超过500ms，不触发触摸效果 。。。
            return ;
        }

        url = $this.data('url');
        if(url) location.href = url;
        return ;

    });

});
</script>

<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?8274693fc4b0b74cc746840db3f22f2f";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>

</body>
</html>