<div class="banner">
</div>
<!-- 关于我们 -->
<div class="main">
	<div class="wrap">
		<div class="tit">
			<h2>关于财猪</h2>
			<span style="left:125px;">ABOUT CAIZHU</span>
		</div>
		<div class="tab" style="padding-left:310px;">
			<ul>
				<li class="hover">关于财猪</li>
				<li><a href="news-detail.html">媒体报道</a></li>
				<li><a href="">更新日志</a></li>
				<div class="clear"></div>
			</ul>
		</div>
		<div class="about">
			<p>财猪是由杭州多麦电子商务有限公司全新推出的一款简单易用的新生活主义理财软件。财猪帮助您更好地使用和管理每一笔收支，培养良好的理财习惯。财猪目前共有iPhone、Android两个版本，更多的版本和功能正在持续开发中。关注财猪的微博和微信，了解更多理财信息。</p>
			<p style="margin-top:20px;">财猪成长记：<span>2015.03，财猪1.1正式版发布</span><span>2015.02，财猪1.0正式版发布</span><span> 2014.10，财猪公测版上线</span></p>
		</div>
	</div>
</div>