<div class="banner">
</div>
<!-- 联系我们 -->
<div class="main">
	<div class="wrap">
		<div class="tit">
			<h2>联系我们</h2>
			<span style="left:130px;">CONTACT US</span>
		</div>
		<div class="contact">
			<img src="/static/images/web/map.jpg">
			<ul>
				<li>杭州多麦电子商务有限公司</li>
				<li>商务合作：business_caizhu#duomai.com</li>
				<li>电话：0571-56638197（9:00-17:30）</li>
				<li>市场推广：market_caizhu#duomai.com</li>
				<li>地址：杭州市江干区九盛路9号东方电子商务园A13幢2层</li>
				<li>媒体报道：media_caizhu#duomai.com</li>
				<li>邮编：310019</li>
				<li style="font-size:12px;">注：发送邮件时，请将#改为@	</li>
				<div class="clear"></div>
			</ul>
		</div>
	</div>
</div>