<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>财猪财务管家 - 下载页</title>
	<link rel="stylesheet" href="/static/css/web/caizhu.css">
	<link rel="stylesheet" href="/static/css/web/jquery.fullPage.css">
	<script src="/static/js/jquery-1.10.2.min.js"></script>
	<script src="/static/js/web/jquery.fullPage.min.js"></script>
</head>
<body>
<!-- 头部 -->
<div class="header header-fixed">
	<div class="wrap">
		<div class="logo"><a href=""><img src="/static/images/web/logo.gif" alt=""></a></div>
		<div class="nav">
			<ul>
                <li><a href="/">首页</a></li>
                <li><a href="/index/down">下载</a></li>
                <li><a href="/index/kefu">客服</a></li>
                <li><a href="/index/about">关于财猪</a></li>
                <li><a href="/index/contact">联系我们</a></li>
                <li><a href="/index/join">加入我们</a></li>
            </ul>
		</div>
	</div>
</div>
<div id="down">
    <div class="section">
		<!-- app下载 -->
		<div class="app-down" style="margin-top:90px;">
			<div class="wrap">
				<a href="" class="andriod"></a>
				<a href="" class="ios"></a>
			</div>
		</div>
    </div>
    <div class="section">
        <div class="down-intro">
        	<div class="wrap">
        		<div class="down-intro-text pos-l" style="color:#1d876e;">
        			<img src="/static/images/web/down-tit-01.jpg" alt="">
        			<p>我最喜欢犒劳自己不停地买买买</p>
        			<p>自从开启理财生活</p>
        			<p>瞬间就让购物基金的尾数多一个零</p>
        		</div>
        		<div class="down-intro-img pos-r">
        			<img src="/static/images/web/down-intro-01.jpg" alt="">
        		</div>
        	</div>
        </div>
    </div>
   <div class="section">
        <div class="down-intro">
        	<div class="wrap">
        		<div class="down-intro-img pos-l">
        			<img src="/static/images/web/down-intro-02.jpg" alt="">
        		</div>
        		<div class="down-intro-text pos-r" style="color:#8c7d3a;">
        			<img src="/static/images/web/down-tit-02.jpg" alt="">
        			<p>我每年都要给自己放假去不同地方旅行</p>
        			<p>自从开启理财生活</p>
        			<p>七星级酒店终于不再是省出来的梦想</p>
        		</div>
        	</div>
        </div>
    </div>
    <div class="section">
        <div class="down-intro">
        	<div class="wrap">
        		<div class="down-intro-text pos-l" style="color:#308088;">
        			<img src="/static/images/web/down-tit-03.jpg" alt="">
        			<p>我最喜欢逛海蜜给我的宝宝添置物品</p>
        			<p>自从开启理财生活</p>
        			<p>家里的储物室都快成了宝宝专属</p>
        		</div>
        		<div class="down-intro-img pos-r">
        			<img src="/static/images/web/down-intro-03.jpg" alt="">
        		</div>
        	</div>
        </div>
    </div>
   <div class="section">
        <div class="down-intro" style="height:50%;">
        	<div class="wrap">
        		<div class="down-intro-img pos-l">
        			<img src="/static/images/web/down-intro-04.jpg" alt="">
        		</div>
        		<div class="down-intro-text pos-r" style="color:#a05236;">
        			<img src="/static/images/web/down-tit-04.jpg" alt="">
        			<p>我最希望家人可以舒舒服服地安享晚年</p>
        			<p>自从开启理财生活</p>
        			<p>今年已经在老家给父母添置了一套新房</p>
        		</div>
        	</div>
        </div>
    </div>
</div>
<script>
		$(function(){
			$('#down').fullpage({
				sectionsColor: ['#18b4ed', '#50db98', '#ffe466', '#35cbd9','#f28c67'],
				'navigation': true,
		});
	})
</script>
</body>
</html>