<div class="banner">
</div>
<!-- 加入我们 -->
<div class="main">
	<div class="wrap">
		<div class="tit">
			<h2>加入我们</h2>
			<span style="left:147px;">JOIN US</span>
		</div>
		<div class="tab" style="padding-left:120px;">
			<ul>
				<li class="hover">技术</li>
				<li>UED</li>
				<li>产品</li>
				<li>市场</li>
				<li>运营</li>
				<li>客服</li>
				<div class="clear"></div>
			</ul>
		</div>
		<div class="tab-content">
			<div class="list job-list" style="display:block;">
				<div class="job-list-item">
					<h3>IOS开发工程师</h3>
					<h4>职位描述: </h4>
					<p>1、iphone/ipad 应用程序的开发和维护； </p>
					<p>2、独立承担或参与iphone/ipad应用程序项目需求分析、设计与实现、相关单元测试和文档书写等工作；</p>
					<p>3、在开发中发现存在的问题能积极沟通与解决，积极参与产品、功能与技术架构的改进； </p>
					<p>4、积极参与工作相关技术的研究、技术规范的制定，提能力；</p>
					<h4>任职要求： </h4>
					<p>1、精通objective-c，1年以上苹果应用程序开发经验，有独立分析和解决问题的能力；</p>
					<p>2、有较强的书面表达能力和口头沟通能力； </p>
					<p>3、有计算机英文基础，阅读英文技术文档的能力； </p>
					<p>4、熟悉Socket网络编程，熟悉TCP、UDP、HTTP、FTP等网络协议； </p>
					<p>5、思路清晰，沟通能力强，有良好的团队意识及服务理念，能承受一定的工作压力；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="job-list-item">
					<h3>Android开发工程师</h3>
					<h4>职位描述: </h4> 
					<p>1、从事基于Android平台系统设计和应用软件开发；</p>
					<p>2、参与产品需求分析并制定技术实施方案，编写需求及设计；</p>
					<p>3、收集软件使用反馈，修正缺陷和BUG，提出优化方案并实施；</p>
					<p>4、按照项目计划，确保质量的情况下完成任务。</p>
					<h4>任职要求：</h4>
					<p>1、熟悉Android OS系统体系结构、Android开发架构和相关API调用；</p>
					<p>2、熟悉Android平台UI设计和常用布局的灵活运用；</p>
					<p>3、2年以上java工作经验，对网络通信协议，多线程，文件IO流等 ；熟悉XML/JSON等常用数据包格式解析，较好的面向对象思维能力；</p>
					<p>4、1.5年以上android 应用开发经验，熟练使用android系统服务，android下的网络通信机制；精通UI组件，界面等特效，独立完成且能达到业界商业界面水准；</p>
					<p>5、有自己app应用挂在android market者优先；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="clear"></div>
				<div class="job-list-item">
					<h3>php工程师</h3>
					<h4>职位描述: </h4>
					<p>1、 使用PHP语言构建产品；</p>
					<p>2、 负责网站的设计、开发与维护。</p>
					<h4>任职要求： </h4>
					<p>1、1年以上PHPWeb项目开发经验，应届生需要有实际项目经验；</p>
					<p>2、熟练掌握PHP，熟悉面向对象的软件设计方法；</p>
					<p>3、熟悉HTML、CSS、Javascript等前端技术，熟悉jquery者优先；</p>
					<p>4、熟悉MySQL数据库应用开发；</p>
					<p>5、有良好的代码习惯，要求结构清晰、命名规范、逻辑性强、代码冗余率低，代码注释清晰；</p>
					<p>6、自学能力强，悟性高，在规定时间内高效完成任务；并具备良好的团队合作精神，可承受一定的工作压力；</p>
					<p>7、喜欢技术，喜欢写代码，有志于成为一个全能型技术大拿。</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="job-list-item">
					<h3>前端工程师</h3>
					<h4>职位描述: </h4>
					<p>1.负责产品的前端代码开发、页面重构以及交互设计逻辑处理。</p>
					<p>2.开发高性能、高兼容性的前端代码，完成脚本通用类库、框架、UI控件的编写，并形成文档。</p>
					<p>3．与产品、UI设计、后台开发人员等协作实现产品功能。</p>
					<p>4.评估、优化网站前端性能。</p>
					<h4>任职要求： </h4>
					<p>1、对Web技术发展有强烈兴趣，对新技术的发展趋势保持关注，能不断学习最新技术；</p>
					<p>2、精通Javascript开发，具有Ajax开发经验，能够优化代码；</p>
					<p>3、精通HTML/CSS开发，熟悉响应式布局优先；</p>
					<p>4、工作认真仔细有激情，有良好的团队合作精神和沟通能力；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="clear"></div>
			</div>
			<div class="list job-list">
				<div class="job-list-item">
					<h3>IOS开发工程师1</h3>
					<h4>职位描述: </h4>
					<p>1、iphone/ipad 应用程序的开发和维护； </p>
					<p>2、独立承担或参与iphone/ipad应用程序项目需求分析、设计与实现、相关单元测试和文档书写等工作；</p>
					<p>3、在开发中发现存在的问题能积极沟通与解决，积极参与产品、功能与技术架构的改进； </p>
					<p>4、积极参与工作相关技术的研究、技术规范的制定，提能力；</p>
					<h4>任职要求： </h4>
					<p>1、精通objective-c，1年以上苹果应用程序开发经验，有独立分析和解决问题的能力；</p>
					<p>2、有较强的书面表达能力和口头沟通能力； </p>
					<p>3、有计算机英文基础，阅读英文技术文档的能力； </p>
					<p>4、熟悉Socket网络编程，熟悉TCP、UDP、HTTP、FTP等网络协议； </p>
					<p>5、思路清晰，沟通能力强，有良好的团队意识及服务理念，能承受一定的工作压力；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="job-list-item">
					<h3>Android开发工程师1</h3>
					<h4>职位描述: </h4> 
					<p>1、从事基于Android平台系统设计和应用软件开发；</p>
					<p>2、参与产品需求分析并制定技术实施方案，编写需求及设计；</p>
					<p>3、收集软件使用反馈，修正缺陷和BUG，提出优化方案并实施；</p>
					<p>4、按照项目计划，确保质量的情况下完成任务。</p>
					<h4>任职要求：</h4>
					<p>1、熟悉Android OS系统体系结构、Android开发架构和相关API调用；</p>
					<p>2、熟悉Android平台UI设计和常用布局的灵活运用；</p>
					<p>3、2年以上java工作经验，对网络通信协议，多线程，文件IO流等 ；熟悉XML/JSON等常用数据包格式解析，较好的面向对象思维能力；</p>
					<p>4、1.5年以上android 应用开发经验，熟练使用android系统服务，android下的网络通信机制；精通UI组件，界面等特效，独立完成且能达到业界商业界面水准；</p>
					<p>5、有自己app应用挂在android market者优先；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="clear"></div>
				<div class="job-list-item">
					<h3>php工程师</h3>
					<h4>职位描述: </h4>
					<p>1、 使用PHP语言构建产品；</p>
					<p>2、 负责网站的设计、开发与维护。</p>
					<h4>任职要求： </h4>
					<p>1、1年以上PHPWeb项目开发经验，应届生需要有实际项目经验；</p>
					<p>2、熟练掌握PHP，熟悉面向对象的软件设计方法；</p>
					<p>3、熟悉HTML、CSS、Javascript等前端技术，熟悉jquery者优先；</p>
					<p>4、熟悉MySQL数据库应用开发；</p>
					<p>5、有良好的代码习惯，要求结构清晰、命名规范、逻辑性强、代码冗余率低，代码注释清晰；</p>
					<p>6、自学能力强，悟性高，在规定时间内高效完成任务；并具备良好的团队合作精神，可承受一定的工作压力；</p>
					<p>7、喜欢技术，喜欢写代码，有志于成为一个全能型技术大拿。</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="job-list-item">
					<h3>前端工程师</h3>
					<h4>职位描述: </h4>
					<p>1.负责产品的前端代码开发、页面重构以及交互设计逻辑处理。</p>
					<p>2.开发高性能、高兼容性的前端代码，完成脚本通用类库、框架、UI控件的编写，并形成文档。</p>
					<p>3．与产品、UI设计、后台开发人员等协作实现产品功能。</p>
					<p>4.评估、优化网站前端性能。</p>
					<h4>任职要求： </h4>
					<p>1、对Web技术发展有强烈兴趣，对新技术的发展趋势保持关注，能不断学习最新技术；</p>
					<p>2、精通Javascript开发，具有Ajax开发经验，能够优化代码；</p>
					<p>3、精通HTML/CSS开发，熟悉响应式布局优先；</p>
					<p>4、工作认真仔细有激情，有良好的团队合作精神和沟通能力；</p>
					<p class="mail-hr">简历发送至Serena@duomai.com</p>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div>