<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 60px;align:center;">
		<form id="privilege_add_form" method="post">
			<table class='form_table'>
				<tr>
					<th>权限描述:</th>
					<td><input class="easyui-validatebox" type="text" name="describe" data-options="required:true"></input></td>
				</tr>
				<tr>
					<th>主标识:</th>
					<td><input class="easyui-validatebox" type="text" name="main_sign" data-options="required:true"></input>(添加成功后不可更改)</td>
				</tr>
				<tr>
					<th>副标识:</th>
					<td><input class="easyui-validatebox" type="text" name="sub_sign" data-options="required:true"></input>(添加成功后不可更改)</td>
				</tr>
				<tr>
					<td colspan='2' class='footbar'>
						
					</td>
				</tr>
			</table>
		</form>

	</div>
	
	<div style="text-align:center;padding:5px">
    	<a href="javascript:void(0)" class="easyui-linkbutton" id="privilege_add_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="privilege_add_form_close">关闭</a>
    </div>
    	    
</div>