<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="channel_add_form" method="post" action="<?php echo $this->url(array('controller'=>'types','action'=>'add'));?>" enctype="multipart/form-data">
            <table class='form_table'>                
                <tr>
                    <th width="30%">频道名称：</th>
                    <td width="70%"><input class="easyui-validatebox" type="text" name="ChannelName" data-options="required:true" size="30" value="" /></td>
                </tr>
                <tr>
                    <th>选择标签：</th>
                    <td>
                        <?php foreach ($this->focusList as $key => $item):?>
                            <?php if($key && $key%4==0): ?>
                                <br/>
                            <?php endif;?>
                            <input type = "checkbox" name="focusIDArr[]" value="<?php echo $item['FocusID'];?>" /><?php echo $item['FocusName']?>&nbsp;&nbsp;&nbsp;&nbsp;
                        <?php endforeach;?>                     
                    </td>    
                </tr>
                <tr>
                    <th>排序：</th>
                    <td><input class="easyui-validatebox" type="number" name="Sort" data-options="required:true" value="0" /></td>
                </tr>

            </table>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="channel_add_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="channel_add_form_close">关闭</a>
        </div>
    </div>
</div>