<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="channel_edit_form" method="post" action="">
           <table class='form_table'>                
                <tr>
                    <th width="20%">频道名称：</th>
                    <td width="80%"><input class="easyui-validatebox" type="text" name="ChannelName" value = "<?php echo $this->channelInfo['ChannelName'];?>" data-options="required:true" size="50" /></td>
                </tr>
                <tr>
                    <th>选择标签：</th>
                    <td>
                        <?php foreach ($this->focusList as $key => $item):?>
                            <?php if($key && $key%4==0): ?>
                                <br/>
                            <?php endif;?>
                            <input type = "checkbox" name="focusIDArr[]" <?php if(in_array($item['FocusID'], $this->selectFocus)):?> checked = "checked" <?php endif;?> value="<?php echo $item['FocusID'];?>" /><?php echo $item['FocusName']?>&nbsp;&nbsp;&nbsp;&nbsp;
                        <?php endforeach;?>                     
                    </td>    
                </tr>
                <tr>
                    <th>排序：</th>
                    <td><input class="easyui-validatebox" type="number" name="Sort" data-options="required:true" value="<?php echo $this->channelInfo['Sort']?>" /></td>
                </tr>            
                <tr>
                    <td colspan='2' class='footbar'>
                        <input type="hidden" name="ChannelID" value="<?php echo $this->channelInfo['ChannelID']?>" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    
    <div style="text-align:center;padding:5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" id="channel_edit_form_save">保存</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" id="channel_edit_form_close">关闭</a>
    </div>
</div>