<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8" />
<meta name="robots" content="all" />
<meta name="keywords" content="财猪" />
<meta name="description" content="财猪" />
<meta name="author" content="财猪" />
<meta name="copyright" content="www.caizhu.com" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />
<meta http-equiv="expires" content="-1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>使用条款和隐私政策</title>
<style>
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,font,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    vertical-align: baseline;
}

img {
    border: none;
    vertical-align: middle;
}

ul,ol,li {
    list-style: none;
}

section,article,aside,header,footer,nav,dialog,figure {
    display: block;
    padding: 0;
    margin: 0;
}

html,body {
    font: 14px/1.4 helvetica,arial,"Microsoft YaHei","微软雅黑",sans-serif;
    -webkit-tap-highlight-color: rgba(255,0,0,0);
    -webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none
    color:#222;
}

body{
    min-width: 300px;
    max-width: 640px;
    margin: 0 auto;
    padding: 0 10px 10px;
}
h1.title{
    line-height: 30px;
}
h1, h2{
    font-size: 16px;
    line-height: 26px;
    margin: 15px 0 5px;
    color: #111;
}
.tos-content{
    line-height: 24px;
    color: #333;
}
.company{
    text-align: right;
    line-height: 26px;
}

p, li{
    margin: 6px 0 0;
}
.indent-one{
	padding: 3px 0 3px 20px;
	line-height: 18px;
}

</style>
</head>
<body>
<div class="bg">
	<div class="container">
		<div class="header">  </div>
		<div class="tos-content">
			<h1 class="title" style="text-align:center;">财猪使用条款及隐私协议</h1>
			<div id="top" class="top">
				<div class="content bold">
						<h1>总则</h1>
						<p style="text-indent:22px">
						欢迎使用杭州小麦金融信息服务有限公司（简称“小麦金融”） 旗下财猪系列产品（包括网站、手机应用等多平台，以下合称“财猪”）为用户提供的各项服务。以下所述条款和条件即构成用户与“小麦金融”就使用服务所达成的协议，一旦用户使用财猪，即表示用户已接受了以下所述的条款和条件。
						</p>
						<p style="text-indent:22px">“小麦金融”根据实际需要有权随时修改下述条款和内容并在财猪上公示，修改后的条款于上线公示时生效。 用户在条款生效后，仍继续使用相关服务的，视为对修改条款和内容的认可。</p>
					</div>
			</div>

			<div id="buttom" class="bottom">
					<div class="content">
					<h2>1、使用规则</h2>
						<ul>
						    <li>
						        1.1用户必须按照申请注册会员的表格，真实、准确、完整的填写用户的资料；维持并及时更新资料，使其保持真实、准确、完整和反应当前情况。倘若用户提供的资料不真实、不准确和不合法或者冒用他人资料，我公司有权保留直接修改资料或者结束用户使用财猪各项服务的权利。
						    </li>
							<li>
							    1.2在注册登记过程中，用户将有权在不违反我国法律法规强制性规定或不违反公序良俗原则的前提下自由选择使用注册帐号并自由设置登录密码。用户对用户的登录密码负有保密和保管义务，并对以用户的注册登录账户进行的一切行为承担法律责任。因此，如果用户发现用户的登录账户密码被盗，请立即通知我公司客服人员按照我公司规定的规范流程帮用户找回密码，用户也可以按照财猪规定的规范流程自行找回密码；如果用户发现用户的账户未经用户的允许被其他任何第三人使用的，请立即修改用户的密码。因用户帐户或密码被盗产生的相关损失，本公司不承担赔偿责任。
							</li>
							<li>
							    1.3用户须对在财猪上所传送信息的真实性、合法性、无害性、有效性等全权负责。财猪所提供的任何信息（包括但不限于财猪官方提供的、财猪用户发布的、财猪邀请的嘉宾提供的），财猪并不能保证其完全实时或完全准确，也不表明财猪证实其描述或赞同其观点。所有内容仅供参考，不构成投资建议或者其他实际的操作意见，用户据此操作所造成的后果自行负责。用户在使用财猪的过程中，因遵守国家有关互联网的法律法规规定，不得进行违法行为，与用户所传播的信息相关的任何法律责任由用户自行承担，我公司对此不承担任何责任。
							</li>
							<li>
                            	1.4用户不得利用财猪服务制作、上载、复制、发送如下内容：
                                	<p class="indent-one">(1) 反对宪法所确定的基本原则的；</p>
                                    <p class="indent-one">(2) 危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；
                                    <p class="indent-one">(3) 损害国家荣誉和利益的；
                                    <p class="indent-one">(4) 煽动民族仇恨、民族歧视，破坏民族团结的；
                                    <p class="indent-one">(5) 破坏国家宗教政策，宣扬邪教和封建迷信的；
                                    <p class="indent-one">(6) 散布谣言，扰乱社会秩序，破坏社会稳定的；
                                    <p class="indent-one">(7) 散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；
                                    <p class="indent-one">(8) 侮辱或者诽谤他人，侵害他人合法权益的；
                                    <p class="indent-one">(9) 含有法律、行政法规禁止的其他内容的信息。
							</li>
                            <li>
                            	1.5鉴于网络的开放性特点，用户在使用财猪服务过程中所发布的内容有可能会被第三方复制、转载、修改或做其他用途而脱离您的预期和控制，用户必须充分意识此类风险的存在，财猪对由此产生的纠纷不予负责。
                            </li>
					  </ul>
					</div>
					<div class="content">
						<h2>2、权利和义务</h2>
							<ul>
                            	<li>
                                	2.1 用户有权根据本协议及财猪上公告的相关规则进行操作，参与活动等其他无特殊限制的服务；用户应当保证在使用财猪各项服务中遵守法律法规，尊重社会公德，遵守诚实信用原则，不扰乱网络秩序；用户同意不对财猪上的信息做商业用途，包括但不限于以复制，传播等方式使用展示在财猪上的任何资料；用户同意接收来自财猪或财猪合作伙伴发出的邮件或信息。</li>
								<li>
                                	2.2我公司有义务在现有技术上维护整个平台的正常运行，并努力提升和改进技术；因网上平台的特殊性，我公司没有义务也无法对所有会员的注册资料，行为及其他事项进行事先的实质性审查；用户因在财猪上的行为与他人产生纠纷或诉讼的，司法部门或行政部门按照法定程序要求本公司提供相关资料的，本公司应积极配合并提供，但用户需了解并确认财猪不对本服务用户之间的纠纷承担任何责任。对于用户在财猪上的不当行为或任何我公司认为应当终止服务的情况，本公司有权删除信息或终止服务，且无须征得用户的同意。
                                </li>
                                <li>
                                	2.3我公司有权对用户的注册资料及在财猪上的行为进行查阅，发现注册资料存在问题或有合理理由怀疑相关行为不当的，有权向用户发出询问及要求修正；我公司转让本协议无需征得用户的同意；在用户使用财猪服务时，财猪有权接收并记录用户的个人信息，包括但不限于IP地址，网站Cookie中的资料及用户所使用财猪手机客户端版本记录等。
                                </li>
                                
							</ul>
					</div>
					<div class="content">
						<h2>3、许可使用权和隐私权</h2>
							<ul>
                                <li>
                                	3.1 用户授予我公司永久的、免费的、完整的许可使用权利，并且有权对该权利进行再授权，使我公司有权在不涉及和泄露用户隐私情况下使用用户的数据参与制作其派生产品，例如但不限于市场调研，消费分析等，以已知或日后开发的任何形式，媒体或技术，纳入其他作品里。
                                </li>
								<li>
                                	3.2保护用户隐私是财猪运营中必须遵守的基本原则，非经用户许可，财猪保证不对外公开或向第三方提供单个用户的注册资料及用户在使用网络服务时存储在财猪的非公开内容，但在下列情况下我公司有权全部或部分披露用户的保密信息：
                                    <p class="indent-one">(1) 遵守有关法律、法规的规定，包括应行政机关、司法机关要求，向第三人或行政机关、司法机关查询时，提供用户的注册信息、用户在财猪上发布的信息内容及其他相关信息。
                                    <p class="indent-one">(2) 保持维护财猪的知识产权和其他重要权利。
                                    <p class="indent-one">(3) 权利人认为用户在财猪上的行为侵犯其合法权利并提出投诉的，可向权利人披露。
                                    <p class="indent-one">(4) 用户出现违反财猪规则，需要向第三方披露的。<p class="indent-one">(5) 根据本协议相关规定或者本公司认为必要的其他情况下。
                                </li>
								<li>
                                	3.3用户知晓并且同意，对于财猪因为计算机系统、网络安全等问题，而导致用户资料意外泄漏，财猪并不对此负责。除非用户能证明，该泄漏是由于财猪的故意行为。
                                </li>
							</ul>
					</div>
					<div class="content"><h2>4、数据储存</h2>
					<ul>
                    	<li>4.1 我公司不对用户在本服务中相关数据的删除或储存失败负责。</li>
						<li>4.2 我公司有权根据实际情况自行决定单个用户在本服务中数据的最长储存期限，并在服务器上为其分配数据最大存储空间等。</li>
					</ul>
					</div>
					<div class="content"><h2>5、内容的所有权</h2>
						<ul>
                        	<li>5.1内容的定义包括：文字、软件、声音、相片、视频、图表等。</li>
                            <li>5.2用户同意，其发布上传到财猪的任何内容，财猪获得其全世界范围内免费的、永久性的、不可撤销的、非独家的许可权。财猪有权将内容用于其他合法用途，包括但不限于部分或者全部地复制、修改、改编、翻译、组装、分拆、推广、分发、广播、表演、演绎、出版。</li>
						</ul>
					</div>
					<div class="content"><h2>6、管辖</h2>
						<p>本协议的成立、生效、履行、解释及纠纷解决，适用中华人民共和国大陆地区法律。因本协议或本公司服务所引起的或与其有关的任何争议，首先应友好协商解决；协商不成的，用户同意将纠纷或争议提交我公司住所地人民法院管辖。</p>
					</div>
                    <div class="content"><h2>7、解释权</h2>
						<ul>
                        	<li>在法律允许的最大范围内，财猪保留对本服务协议的最终解释权。</li>
						</ul>
                        <p class="company">杭州小麦金融信息服务有限公司</p>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
</body>
</html>