<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8" />
<meta name="robots" content="all" />
<meta name="keywords" content="财猪" />
<meta name="description" content="财猪" />
<meta name="author" content="财猪" />
<meta name="copyright" content="www.caizhu.com" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />
<meta http-equiv="expires" content="-1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>财猪内容发布规范</title>
<style>
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,font,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    vertical-align: baseline;
}

img {
    border: none;
    vertical-align: middle;
}

ul,ol,li {
    list-style: none;
}

section,article,aside,header,footer,nav,dialog,figure {
    display: block;
    padding: 0;
    margin: 0;
}

html,body {
    font: 14px/1.4 helvetica,arial,"Microsoft YaHei","微软雅黑",sans-serif;
    -webkit-tap-highlight-color: rgba(255,0,0,0);
    -webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none
    color:#222;
}

body{
    min-width: 300px;
    max-width: 640px;
    margin: 0 auto;
    padding: 0 10px 10px;
}
h1.title{
    line-height: 30px;
}
h1, h2{
    font-size: 16px;
    line-height: 26px;
    margin: 15px 0 5px;
    color: #111;
}
.tos-content{
    line-height: 24px;
    color: #333;
}
.company{
    text-align: right;
    line-height: 26px;
}

p, li{
    margin: 6px 0 0;
}
.indent-one{
	padding: 3px 0 3px 20px;
	line-height: 18px;
}

/* 财猪话题公约 */
.gongyue-tit{
	font-weight: bold;
}
/*
.inner-inner-list{
	padding: 0 0 0 10px
}
*/

</style>
</head>
<body>
<div class="bg">
	<div class="container">
		<div class="header">  </div>
		<div class="tos-content">
			<h1 class="title" style="text-align:center;">《财猪内容发布规范》</h1>
			<div id="top" class="top">
				<div class="content bold">
						<p style="text-indent:22px">为构建和谐、法治、健康的网络环境，维护财猪话题秩序，更好的保障用户合法权益，财猪依据并贯彻《全国人民代表大会常务委员会关于加强网络信息保护的决定》的文件精神，与用户共同制定本规范。</p>
					</div>
			</div>

			<div id="buttom" class="bottom">
				<div class="content">
					<h2>第一章  总　则</h2>
					<ul>
						<li>
							<p class="gongyue-tit">第一条</p>
							<p>财猪是由小麦金融信息服务有限公司创建、运行的金融服务社交网络平台(下称本平台)。</p>
						</li>
						<li>
							<p class="gongyue-tit">第二条</p>
							<p>财猪用户是指财猪的注册用户，其行为需遵守本公约；未注册者在本平台的活动亦参照本规范。</p>
						</li>
						<li>
							<p class="gongyue-tit">第三条</p>
							<p>财猪用户在本平台的活动不得违反现行法律法规。本平台将按照相关法律法规及用户注册协议，配合司法机关维护被侵权人合法权益。</p>
						</li>

					</ul>
				</div>

				<div class="content">
					<h2>第二章 用户行为规范</h2>
					<ul>
						<li>
							<p class="gongyue-tit">第四条</p>
							<p>财猪用户拥有发布话题、观点、文章等内容的权利，但不得发布含有以下内容的信息：</p>
							<ul class="inner-list">
								<li>
									<p class="gongyue-er">一、禁止发布危害信息。危害信息主要包括：</p>
									<ul class="inner-inner-list">
										<li>
											<p class="gongyue-san">(一) 根据现行法律法规，危害国家及社会安全的信息(简称“敏感信息”)，主要表现为：</p>
											<p>1. 反对宪法确定的基本原则；</p>
											<p>2. 危害国家统一、主权和领土完整；</p>
											<p>3. 泄露国家秘密、危害国家安全或者损害国家荣誉和利益；</p>
											<p>4. 煽动民族仇恨、民族歧视，破坏民族团结，或者侵害民族风俗、习惯；</p>
											<p>5. 破坏国家宗教政策，宣扬邪教、迷信；</p>
											<p>6. 散布谣言，扰乱社会秩序，破坏社会稳定；</p>
											<p>7. 宣扬赌博、暴力、凶杀、恐怖或者教唆犯罪；</p>
											<p>8. 煽动非法集会、结社、游行、示威、聚众扰乱社会秩序；</p>
											<p>9. 含有法律、行政法规和国家规定禁止的其他内容。</p>
										</li>

										<li>
											<p class="gongyue-san">(二) 不安全信息，包括可能对用户财产安全或信息安全造成损失的内容，主要表现为：</p>
											<p>1.含钓鱼网站链接的相关内容；</p>
											<p>2.含木马、病毒网站链接及相关内容；</p>
											<p>3.含潜在危险、窃取用户隐私等相关内容；</p>
											<p>4.影响用户体验或被大量用户举报的未经审核的外链、二维码及其他多媒体等其他内容；</p>
										</li>

										<li>
											<p class="gongyue-san">(三) 垃圾营销信息，是指以营利为目的，在与用户建立或维持关系的过程中，所产生的影响用户体验，扰乱财猪话题秩序的信息和行为，其中包括垃圾信息、恶意行为和骚扰用户的营销信息，主要表现为：</p>
											<p>1. 从事买卖粉丝及相关业务；</p>
											<p>2. 从事刷评论、刷转发、刷搜索、刷投票、刷有奖活动业务；</p>
											<p>3. 通过机器或软件等非人力手段对他人页面大量发送广告信息；</p>
											<p>4. 虚假中奖信息；</p>
											<p>5. 机器抓取发送的无意义内容、重复内容；</p>
											<p>6. 利用系统漏洞干扰财猪正常秩序的行为。如：盗用他人账号、强制他人关注等；</p>
											<p>7. 影响用户体验或被大量用户举报的，其性质属于推销宣传推广的营销信息。</p>
											<p>8、形式不限于图文帖、水印、二维码、头像等</p>
										</li>

										<li>
											<p class="gongyue-san">(四) 淫秽色情信息，主要表现为：</p>
											<p>1. 淫秽：具体描绘性行为或露骨宣扬色情的诲淫性信息。</p>
											<p>2. 色情：露三点的图片、视频，带有色情意味、暗示、挑逗和引起他人类似感受的音频、文字。</p>
										</li>
									</ul>
								</li>
								<li>
									<p class="gongyue-er">二、禁止发布不实信息。不实信息主要表现为：</p>
									<ul class="inner-inner-list">
										<li>
											<p class="gongyue-san">(一) 整体失实：事件本身系子虚乌有。</p>
											<p class="gongyue-san">(二) 捏造细节：捏造细节使整个事件被扭曲。</p>
											<p class="gongyue-san">(三) 图文不符：通过错误的图文搭配误导他人。</p>
											<p class="gongyue-san">(四) 夸大事实：在描述中对事实夸大其词，误导他人。</p>
											<p class="gongyue-san">(五) 过期信息：将已得到解决的事件作为新消息发布，并略去已产生的结果。</p>
											<p class="gongyue-san">(六) 信息残缺：隐藏部分事实，以不完整的信息误导他人。</p>
											<p class="gongyue-san">(七)断章取义：将部分事实加上推测作为事实发布。</p>
										</li>
									</ul>
								</li>
							</ul>
						</li>
						<li>
							<p class="gongyue-tit">第五条</p>
							<p>用户应尊重他人名誉权，不得对他人进行人身攻击。</p>
							<p>人身攻击，主要表现为：</p>
							<p>1. 侮辱：以侮辱性言论伤害他人。</p>
							<p>2. 诽谤：刻意捏造信息破坏他人名誉。误解不适用本条规定。</p>
							<p>3. 肖像篡改：修改他人肖像且令本人不能接受。</p>
							<p>转发他人发布的含有人身攻击内容的话题或观点，但没有继续人身攻击的，该转发不构成人身攻击，但接到当事人举报后可删除。</p>
						</li>
						<li>
							<p class="gongyue-tit">第六条</p>
							<p>用户应尊重他人隐私权，不得侵害他人隐私。涉及公众利益或当事人已公开或授权公开的除外。</p>
							<p>隐私包括真实姓名、身份证号、电话号码、家庭住址及用户不愿公开的其他个人信息。还包括他人不愿被知悉的不危害社会的信息。如：性取向、生理及心理缺陷、财产状况、信用卡、电子消费卡、上网卡、上网帐号和密码、交易账号和密码、网上购物使用的帐号和密码、IP地址、浏览网页的踪迹或活动内容、私生活镜头以及社会关系等，他人可通过合法公开渠道得知的或涉及公共利益的除外。</p>
						</li>
						<li>
							<p class="gongyue-tit">第七条</p>
							<p>用户应尊重他人肖像权，未经他人同意不得擅自使用或修改其肖像。</p>
						</li>
						<li>
							<p class="gongyue-tit">第八条</p>
							<p>用户应尊重他人安宁权，不得利用本平台骚扰他人。不应以评论、消息、点赞、@XX等方式对他人反复发送重复、近似、诉求相同的信息。</p>
						</li>
						<li>
							<p class="gongyue-tit">第九条</p>
							<p>用户应尊重他人著作权。发布他人原创内容需注明出处或带有明显转载标识。</p>
							<p>原创内容暂指首发于财猪平台的内容，不包括修改、整合的图片等。</p>
						</li>


					</ul>
				</div>

				<div class="content"><h2>第三章 违规行为处置</h2>
					<ul>
						<li>
							<p class="gongyue-tit">第十条</p>
							<p>处罚措施包括：</p>
							<p>违规处理：内容处理和帐号处理。</p>
							<p>内容处理：删除、屏蔽、禁言等。</p>
							<p>帐号处理：禁止发布观点、禁止创建话题等其他功能的使用。</p>
						</li>
					</ul>
				</div>

				<div class="content"><h2>第四章 附则</h2>
					<ul>
						<li>
							<p>1、财猪为免费的信息发布平台，不负任何连带责任，请仔细甄别信息内容；</p>
							<p>2、为了维护财猪的良好氛围，避免用户受到人身及财产上的损失，欢迎各位用户积极举报违规行为；</p>
							<p>3、对于涉及公约细则被处罚的用户，财猪官方不接受也不回应申诉；</p>
							<p>4、《财猪内容发布规范》也将随着管理团队的成长而不断更新；</p>
							<p>5、财猪管理团队对《财猪内容发布规范》具有最终解释权。</p>
						</li>
					</ul>
				</div>

			</div>

			</div>
		</div>
	</div>
</div>
</body>
</html>