<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 60px;align:center;">
	
		<form id="admin_add_form" method="post" action="">
			<table class='form_table'>
				<tr>
					<th>用户名:</th>
					<td><input class="easyui-validatebox" type="text" name="name" data-options="required:true"></input></td>
				</tr>
				<tr>
					<th>密码:</th>
					<td><input class="easyui-validatebox" type="password" name="password" data-options="required:true"></input></td>
				</tr>
				<tr>
					<th>确认密码:</th>
					<td><input class="easyui-validatebox" type="password" name="repassword" data-options="required:true"></input></td>
				</tr>
				
				<tr>
					<th>工号:</th>
					<td><input class="easyui_validatebox" type="text" name="empno"></input></td>
				</tr>
				
				<tr>
					<th>联系电话:</th>
					<td><input class="easyui_validatebox" type="text" name="telphone"></input></td>
				</tr>
			</table>
		</form>

	</div>
	
	<div style="text-align:center;padding:5px">
    	<a href="javascript:void(0)" class="easyui-linkbutton" id="admin_add_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="admin_add_form_close">关闭</a>
    </div>
	
</div>