    <div class="main-right fr">
        <h2 class="content-tit clearfix p-rela nobd">
            内容管理
            <span class="article-tit-do">
                <a class="selected" href = "/article/index">头条文章</a>
                <?php if($this->authenticateType>1):?><span class="at-separate">|</span>
                <a href="/activity/index">线下活动</a><?php endif;?>
                <?php if($this->authenticateType==2):?><span class="at-separate">|</span>
                <a href="/counsel/index">询财服务</a><?php endif;?>

                <a class="article-todo" href="/article/add">创建文章</a>
            </span>
        </h2>

        <ul class="article-list">
        <?php foreach ($this->articleInfo as $value):?>
            <li class="article-one clearfix" data-id="<?php echo $value['AID'];?>" data-charge="<?php echo $value['IsCharge'];?>">
                <div class="ao-pic"><img src="<?php echo $value['Cover'].'?imageView2/0/w/165/h/120';?>" alt="图片" /></div>
                <div class="ao-info">
                    <div class="ao-info-tit clearfix">
                        <a class="" href="/article/detail?articleID=<?php echo $value['AID']?>">
                            <?php echo $value['Title'];?>

                            <?php if($value['IsCharge'] == 1):?>
                                <span class="ao-type-one">收费</span>
                            <?php endif;?>
                            <?php if($value['IsTimedPublish'] == 1):?>
                                <span class="ao-type-one">定时发布</span>
                            <?php endif;?>

                        </a>
                        <span class="ao-doa hide">
                            <a href="">删除</a>
                        </span>
                    </div>
                    <p class="ao-info-data">
                        <?php echo $value['PublishTime'];?>
                        <span class="ao-do-view"><?php echo $value['ReadNum'];?></span>
                        <span class="ao-do-zan"><?php echo $value['PraiseNum'];?></span>
                        <span class="ao-do-comment"><?php echo $value['CommentNum'];?></span>
                    </p>
                    <p class="ao-info-des"><?php echo $value['Content'];?></p>
                    <?php if($value['MemberID']==8527 || $value['MemberID']==6131):?>
                    <a class="ao-draft-rig" href="/article/add?articleID=<?php echo $value['AID'];?>">编辑</a>
                    <?php endif;?>
                </div>
            </li>
         <?php endforeach;?>
        </ul>

        <?=$this->paginationControl($this->articleInfo, 'Sliding', 'page.phtml')?>

    </div> <!-- main-right -->


<script>

// DEL - action
var $listBox = $('.article-list');

$listBox.children().each(function(){
    var $this = $(this),
        flag = $this.data('charge');
    if(flag == 0){
        $this.find('.ao-doa').removeClass('hide');
    };
})

$listBox.delegate('.ao-doa a', 'click', function(){
    var id,
        $this = $(this),
        $parents,
        commentNum,
        pStr = '删除的文章将不可恢复，确定删除吗？',
        pStr01 = '删除文章，评论也会随之删除，确定删除吗？';

    $parents = $this.parents('li');
    id = $parents.data('id');
    commentNum = $parents.find('.ao-do-comment').text();
    commentNum = parseInt(commentNum);

    if(commentNum > 0){
        definedPrompt000(pStr01, function(){
            delOne(id, $parents);
        });
    }else{
        definedPrompt000(pStr, function(){
            delOne(id, $parents);
        });
    }

    return false;

});

function delOne(id, obj){
    $.ajax({
        url: '/article/delete',
        type: 'post',
        dataType :'json',
        data:{
            articleID: id
        },
        dataType: 'json',
        success: function(d){
            if(d.flag == 1){
                obj.remove();
            }else{
                definedPrompt(d.msg);
            }
        },
        error: function(){
            definedPrompt('网络错误');
        }

    });
}


</script>