 <div class="main-right fr">
        <h2 class="content-tit clearfix p-rela">
            草稿箱<span class="article-tit-do"><a  class="selected" href="article">文章(<?php echo $this->draftNum['articleNum']; ?>)</a>
            <?php if($this->authenticateType>1):?><span class="at-separate">|</span><a  href="activity">活动(<?php echo $this->draftNum['activityNum']; ?>)</a><?php endif;?>
            <?php if($this->authenticateType==2):?><span class="at-separate">|</span><a  href="counsel">询财服务(<?php echo $this->draftNum['counselNum']; ?>)</a><?php endif;?>
            </span>
        </h2>

        <ul class="article-list">
        <?php foreach ($this->dataList as $value):?>
            <li class="article-one clearfix">
                <div class="ao-pic"><img src="<?php echo $value['Cover'];?>" alt="图片" /></div>
                <div class="ao-info">
                    <div class="ao-info-tit ao-draft clearfix">
                        <div class="ao-draft-lef">
                            <a href="/article/detail?articleID=<?php echo $value['AID']?>">
                                <?php echo $value['Title']?>

                                <?php if($value['IsCharge'] == 1):?>
                                    <span class="ao-type-one">收费</span>
                                <?php endif;?>
                                <?php if($value['IsTimedPublish'] == 1):?>
                                    <span class="ao-type-one">定时发布</span>
                                <?php endif;?>
                            </a>
                        </div>

                        <a class="ao-draft-rig ao-draft-del" data-id="<?php echo $value['AID'];?>">删除</a>
                        <a class="ao-draft-rig" href="/article/add?articleID=<?php echo $value['AID'];?>">编辑</a>

                    </div>
                    <p class="ao-info-data"><?php echo $value['CreateTime'];?></p>
                    <p class="ao-info-des"><?php echo $value['Content'];?></p>
                </div>
            </li>
       <?php endforeach;?> 
        </ul>

       <?=$this->paginationControl($this->dataList, 'Sliding', 'page.phtml')?>

    </div> <!-- main-right -->


<script>
$('.ao-draft-del').click(function(){

    var $this = $(this),
        id = $this.data('id');


    $promptBox.find('#ppt-09').removeClass(hide);
    $promptBox.removeClass(hide);

    $('body').delegate('#ppt-09 .ppt-do span', 'click', function(){
    	$.ajax({
            url: '/article/delete',
            type: 'post',
            dataType :'json',
            data:{
                articleID: id
            },
            dataType: 'json',
            success: function(d){
                if(d.flag == 1){
                    $this.parents('li').remove();
                    $promptBox.addClass(hide);
                    $promptBox.find('#ppt-09').addClass(hide);
                }else{
                    definedPrompt(d.msg);
                }
            },
            error: function(){
                definedPrompt('网络错误');
            }

        });
    });


});

</script>