
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
        <form id="authenticate_check_form" method="post" action="" enctype="multipart/form-data">
            <table class='form_table'>                
                <tr>
                    <td width="40%">    
                        <select name="Status">
                            <?php if($this->authenticateInfo['Status']==0):?>
                                <option value="1">通过</option>
                                <option value="2">拒绝</option>
                            <?php elseif($this->authenticateInfo['Status']==2):?>                                       
                                <option value="1">通过</option>
                            <?php endif;?>
                        </select>
                    </td>
                </tr>
                <tr id = "reason"  style="display:none" >
                    <td colspan="2" valign="center"><br/>理由：&nbsp;&nbsp;<textarea name = "Remark"　cols="20" rows="3"></textarea></td>
                </tr>
               
                <tr>
                    <td colspan='2' class='footbar'>
                    <input type="hidden" name="AuthenticateID" value="<?php echo $this->authenticate_id;?>"/>
                    </td>
                </tr>
            </table>
        </form>
        <div style="text-align:center;padding:5px ">
            <a href="javascript:void(0)" class="easyui-linkbutton" id="authenticate_check_form_save">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" id="authenticate_check_form_close">关闭</a>
        </div>
    </div>
</div>
<script type="text/javascript">

    $("select[name='Status']").change(function(){
        var status = $(this).val();
        if(status==1){
            document.getElementById("reason").style.display = 'none';
        }else{
            document.getElementById("reason").style.display = '';
        }
    });

</script>