<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">
		<form id="column_check_form" method="post" action="" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<th width="20%">审核状态：</th>
					<td width="80%">
						<select name="CheckStatus">
							<?php if ($this->status == 0): ?>
								<option value="1">通过</option>
								<option value="2">失败</option>
							<?php endif; ?>
						</select>
					</td>
				</tr>
				<tr>
					<th width="20%">审核备注：</th>
					<td width="80%">
						<select name="CheckRemark" style="width:150px">
							<?php if ($this->status == 0): ?>
								<option value="审核成功" selected="selected">审核成功</option>
							<?php endif; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan='2' class='footbar'>
						<input type="hidden" name="ColumnID" value="<?php echo $this->column_id; ?>"/>
						<input type="hidden" name="member_id" value="<?php echo $this->member_id; ?>"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<div style="text-align:center;padding:5px">
		<a href="javascript:void(0)" class="easyui-linkbutton" id="column_check_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="column_check_form_close">关闭</a>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
        $('select[name="CheckStatus"]').change(function(){
            $('select[name="CheckRemark"]').empty();
            if($(this).val()==1){
                $('select[name="CheckRemark"]').append("<option value='审核成功'>审核成功</option>");
            }else{
                $('select[name="CheckRemark"]').append("<option value='理财号名称已存在'>理财号名称已存在</option>"+
								"<option value='理财号头像不符合要求'>理财号头像不符合要求</option>"+
								"<option value='理财号简介不符合要求'>理财号简介不符合要求</option>");
            }
        })
    })
</script>