


<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 60px;align:center;">
    
        <form id="articlecategory_add_form" method="post" action="">
            <table class='form_table'>
                    <tr>
                    <th>上级分类：</th>
                    <td><select name="ret[PID]" class="easyui-validatebox" data-options="required:true">
                    <option value="0">请选择</option>
                    <? foreach($this->cate as $item):?><option value="<?=$item['CategoryID']?>"><?=$item['Name']?></option><?endforeach;?>
                    </select></td>
                    </tr>
                    
                <tr>
                    <th>名称:</th>
                    <td><input class="easyui-validatebox" type="text" name="ret[Name]" data-options="required:true" size="26"></input></td>
                </tr>
                
                <tr>
                    <th>名称[英文]:</th>
                    <td><input class="easyui-validatebox" type="text" name="ret[NameEn]" data-options="required:true" size="26"></input></td>
                </tr>
                
                <tr>
                    <td colspan='2' class='footbar'>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    
    <div style="text-align:center;padding:5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" id="articlecategory_add_form_save">保存</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" id="articlecategory_add_form_close">关闭</a>
    </div>
    
</div>