<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 10px;align:center;">
		<form id="finance_add_form" method="post">
			<table class='form_table'>
				<tr>
					<td colspan='2'><strong>&nbsp;&nbsp;&nbsp;&nbsp;会员ID:</strong>&nbsp;&nbsp;<input class="easyui-validatebox" type="text" name="member_id" data-options="required:true" size="30"/>
				</tr>
                <tr>	
					<td colspan='2'><strong>明细类型:</strong>&nbsp;
						<select name="financeType" style="width:152px;">  
                            <option value="1">会员充值</option>
                            <option value="2">会员提现</option>
						</select> 
					</td>
				</tr>
				<tr>
					<td colspan='2'>
						<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;金额:</strong>&nbsp;&nbsp;<input class="easyui-validatebox" type="text" name="amount" data-options="required:true"  size="30"/>&nbsp;元
                        <!--<strong>货币单位:</strong>
						<select name="currency" style="width:100px;">  
							    <option value="CNY">人民币</option>
							    <option value="USD">美元</option>  
						</select>-->
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<strong>备注说明:</strong>&nbsp;
						<textarea rows="6" cols="45" name="remark"></textarea>
					</td>
				</tr>
			</table>
		</form>
	</div>
	
	<div style="text-align:center;padding:5px">
    	<a href="javascript:void(0)" class="easyui-linkbutton" id="finance_add_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="finance_add_form_close">关闭</a>
    </div>
	
</div>