<div class="easyui-panel" style="border:0px;">
	<div style="padding:5px 0 5px 5px;align:center;">
		<form id="reject_refund_form" method="post">
			<table class='form_table'>				
				<tr>
					<td colspan="2">
						<strong>请写明拒绝原因:</strong><br/>
						<textarea rows="5" cols="50" name="remark"></textarea>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<input type="hidden" name="member_id" value="<?php echo $this->member_id;?>"/>
						<input type="hidden" name="application_id" value="<?php echo $this->application_id;?>" />
						<input type="hidden" name="status" value="<?php echo $this->status;?>" />
					</td>
				<tr>
			</table>
		</form>
	</div>
	
	<div style="text-align:center;padding:5px">
    	<a href="javascript:void(0)" class="easyui-linkbutton" id="reject_refund_form_save">拒绝提现</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="reject_refund_form_close">关闭</a>
    </div>
	
</div>