<?php $cardInfo = $this->cardInfo; ?>
<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">
		<form id="set_city_form" method="post">
			<table class='form_table' cellspacing="15">				
				<tr>
					<th>省份:</th>
					<td>
						<input type="text" value="<?php echo $cardInfo['province'];?>" name="province" size=12 >
					</td>
				</tr>
				<tr>
					<th>城市:</th>
					<td><input name="city" value="<?php echo $cardInfo['city'];?>" size=12 /></td>
				</tr>
			</table>
            <input type="hidden" name="bid" value="<?php echo $cardInfo['bid'];?>"/>
		</form>
	</div>
	
	<div style="text-align:center;padding:5px">
    	<a href="javascript:void(0)" class="easyui-linkbutton" id="set_city_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="set_city_close">关闭</a>
    </div>
	
</div>