#!/bin/sh
#auth wujp
#define simba erp request percent minute
#pv|api|connect(pv+api)

if [ $# = 0 ];then
   echo "sorry,sir. please specify arguments:"
   exit 1
fi

#判断bash本版,大于4.0 否则 declare -A选项无效 版本号比较
bash_version=`bash --version |awk -F[.] '/GNU bash/{print $1}'`
if [ `echo "${bash_version:${#bash_version}-1}>=4"|bc` = 0 ];then
   echo 'sorry,sir.the bash version mush gt 4.0,please update bash!'
   exit 1
fi

nginx_log_path=/app/nginx/logs/simba_access.log

declare -A month_map
month_map=([01]=Jan [02]=Feb [03]=Mar [04]=Apr [05]=May [06]=Jun [07]=Jul [08]=Aug [09]=Sep [10]=Oct [11]=Nov [12]=Dec)

#默认获取前一分钟的日志
now=`date -d "-1 min" "+%d/%m/%Y:%H:%M"`
month=`echo $now|cut -b '4-5'`

map=`echo $now|cut -b '1-3'`${month_map[$month]}`echo $now|cut -b '6-'`

case $1 in
   pv)
     result=`cat $nginx_log_path |grep $map |egrep "GET /view.php|GET /ngx_tpl.php"|wc -l`
     echo $result
   ;;
   api)
      result=`cat $nginx_log_path |grep $map |grep "GET /api"|wc -l`
      echo $result
   ;;
   connect)
      result=`cat $nginx_log_path |grep $map |egrep "GET /view.php|GET /ngx_tpl.php|GET /api"|wc -l`
      echo $result
   ;;
   *)
   echo "Usage:$2(pv|api|connect)"
   ;;
esac