<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">
		<form id="column_notice_edit_form" method="post" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<th width="20%">公告标题：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="Title"
					                       value="<?php echo $this->column_notice['Title']; ?>"
					                       data-options="required:true"
					                       size="50"/></td>
				</tr>
				<tr>
					<th width="20%">公告内容：</th>
					<td width="80%">
						<textarea class="easyui-validatebox validatebox-text" style="width: 350px;height: 300px;" name="Content" ><?php echo trim($this->column_notice['Content']); ?></textarea>
					</td>
				</tr>
				<tr>
					<th>类型：</th>
					<td>
						<select name="Type">
							<option
								value="1" <?php if ($this->column_notice['Type'] == 1): ?> selected="selected" <?php endif; ?>>
								公告
							</option>
							<option
								value="2" <?php if ($this->column_notice['Type'] == 2): ?> selected="selected" <?php endif; ?>>
								通知
							</option>
						</select>
					</td>
				</tr>
				<tr>
					<th>状态：</th>
					<td>
						<select name="Status">
							<option
								value="0" <?php if ($this->column_notice['Status'] == 0): ?> selected="selected" <?php endif; ?>>
								无效
							</option>
							<option
								value="1" <?php if ($this->column_notice['Status'] == 1): ?> selected="selected" <?php endif; ?>>
								有效
							</option>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan='2' class='footbar'>
						<input type="hidden" name="NoticeID" value="<?php echo $this->column_notice['NoticeID'] ?>"/>
					</td>
				</tr>
			</table>
		</form>
	</div>

	<div style="text-align:center;padding:5px">
		<a href="javascript:void(0)" class="easyui-linkbutton" id="column_notice_edit_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="column_notice_edit_form_close">关闭</a>
	</div>

</div>