<div class="main-right fr">
        <h2 class="content-tit">消息通知</h2>

        <h1 class="article-tit"><?php echo $this->noticeInfo['Title'];?> </h1>
        <div class="article-minor clearfix">
            <div class="am-info fr">
                <span>更新时间：<?php echo $this->noticeInfo['CreateTime'];?></span>
                <span class="ml20">发表者：财猪</span>
            </div>
        </div>

        <div class="article-detail">
        <?php echo $this->noticeInfo['Content'];?>

        </div>

    </div>