<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">
		<form id="column_activity_edit_form" method="post" action="" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<td width="40%">
						<select name="Status">
							<option value="0" <?php if ($this->status == 0) echo 'selected="selected"' ?>>删除</option>
							<option value="1" <?php if ($this->status == 1) echo 'selected="selected"' ?>>正常</option>
							<option value="2" <?php if ($this->status == 2) echo 'selected="selected"' ?>>保存草稿</option>
							<option value="3" <?php if ($this->status == 3) echo 'selected="selected"' ?>>暂存预览</option>
						</select>
					</td>
					<td>
						<a href="javascript:void(0)" class="easyui-linkbutton"
						   id="column_activity_edit_form_save">保存</a>
						<a href="javascript:void(0)" class="easyui-linkbutton"
						   id="column_activity_edit_form_close">关闭</a>
					</td>
				</tr>
				<tr>
					<td colspan='2' class='footbar'>
						<input type="hidden" name="AID" value="<?php echo $this->aid; ?>"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>