<!--内容部分-->
<table id="column_activity_list"></table>
<div id="column_activity_list_toolbar">
	<a id="refresh" class="easyui-linkbutton" iconCls="icon-reload" plain="true">刷新</a>
	标题：
	<input type="text" value="" name="Title" size="20"/> &nbsp;&nbsp;

	状态：
	<select name="Status">
		<option value="">所有</option>
		<option value="0">删除</option>
		<option value="1">正常</option>
		<option value="2">保存草稿</option>
		<option value="3">暂存预览</option>
	</select>&nbsp;&nbsp;
	创建时间：
	<input class="easyui-datetimebox" type="text" name="Start_CreateTime" value="" data-options=""/>
	至&nbsp;<input class="easyui-datetimebox" type="text" name="End_CreateTime" value="" data-options=""/>
	<a class="easyui-linkbutton" iconCls="icon-search" id="search">搜索</a>
</div>

<div id="column_activity_view"></div>
<div id="img_dialog" class="easyui-dialog" title="img" closed="true" data-options="resizable:'true'"
     style="width: 400px;height: 400px;">
</div>

<script type="text/javascript">
	var column_activityObj = {
		//数据加载url
		'loadUrl': '<?php echo $this->url(array('controller'=>'column-activity','action'=>'list'));?>',
		'editUrl': '<?php echo $this->url(array('controller'=>'column-activity','action'=>'edit'));?>',
		'adsLink': '<?php echo $this->url(array('controller'=>'column-activity','action'=>'ads-link'));?>',

		//审核专栏
		'edit_feature': {
			'width': 300,
			'height': 80,
			'title': '编辑状态'
		},

		//广告链接
		adsHandler: function (id) {
			var _THIS_ = this;
			_THIS_.view.window({
				'href': _THIS_.adsLink + '?AID=' + id,
				'width': 500,
				'height': 150,
				'modal': true,
				'resizable': false,
				'cache': false,
				'title': '复制链接',
				'onLoad': function () {
					if (window.clipboardData) {
						$('.copy_btn').click(function () {
							var tempID = $(this).attr('data-value-id');
							window.clipboardData.setData("Text", $("#" + tempID).val());
							alert('复制成功！');
						});
					} else {
						$(".copy_btn").zclip({
							path: '/static/js/ZeroClipboard.swf',
							copy: function () {
								var tempID = $(this).attr('data-value-id');
								return $("input#" + tempID).val();
								//return $(this).prev('input').val();
							},
							afterCopy: function () {
								alert('复制成功！');
							}
						});
					}
				}
			});
		},

		//加载数据
		'showData': function () {
			var _THIS_ = this;
			_THIS_.container.datagrid({

				//是否条纹显示
				striped: true,
				//加载提示信息
				loadMsg: '正在加载...',
				//列是否自适应
				//fitColumns:true,
				rownumbers: true,
				fit: true,
				//是否单行选择
				singleSelect: true,

				idField: 'AID',

				url: _THIS_.loadUrl,

				toolbar: '#column_activity_list_toolbar',

				//设置列
				columns: [[
					{field: 'AID', title: '文章ID', width: 40},
					{field: 'UserName', title: '会员名称', width: 60},
					{field: 'ColumnID', title: '专栏ID', width: 40},
					{field: 'Title', title: '标题', width: 150},
					{field: 'StartTime', title: '活动开始时间', width: 150},
					{field: 'EndTime', title: '活动截止时间', width: 150},
					{field: 'Province', title: '省', width: 50},
					{field: 'City', title: '市', width: 50},
					{field: 'DetailAdress', title: '街道地址', width: 150},
					{field: 'Cover', title: '封面', width: 150},
					{field: 'LimitNum', title: '人数限制', width: 60},
					{field: 'Content', title: '内容', width: 150},
					{field: 'LimitTime', title: '报名截止时间', width: 150},
					{
						field: 'IsRecommend', title: '允许推荐', width: 70, formatter: function (value, rec, index) {
						var IsRecommend = '';
						switch (IsRecommend) {
							case '0':
								IsRecommend = '否';
								break;
							case '1':
								IsRecommend = '是';
								break;
						}
						return IsRecommend;
					}
					},
					{field: 'ReadNum', title: '阅读数量', width: 60},
					{field: 'EnrollNum', title: '报名人数', width: 60},
					{field: 'ShareNum', title: '分享数量', width: 60},
					{
						field: 'IsUsername', title: '需要姓名', width: 70, formatter: function (value, rec, index) {
						var IsUsername = '';
						switch (IsUsername) {
							case '0':
								IsUsername = '否';
								break;
							case '1':
								IsUsername = '是';
								break;
						}
						return IsUsername;
					}
					},
					{
						field: 'IsMobile', title: '需要手机号', width: 70, formatter: function (value, rec, index) {
						var IsMobile = '';
						switch (IsMobile) {
							case '0':
								IsMobile = '否';
								break;
							case '1':
								IsMobile = '是';
								break;
						}
						return IsMobile;
					}
					},
					{
						field: 'IsValidMobile', title: '需要验证', width: 70, formatter: function (value, rec, index) {
						var IsValidMobile = '';
						switch (IsValidMobile) {
							case '0':
								IsValidMobile = '否';
								break;
							case '1':
								IsValidMobile = '是';
								break;
						}
						return IsValidMobile;
					}
					},
					{
						field: 'Status', title: '状态', width: 70, formatter: function (value, rec, index) {
						var status = '';
						switch (value) {
							case '0':
								status = '删除';
								break;
							case '1':
								status = '正常';
								break;
							case '2':
								status = '草稿';
								break;
							case '3':
								status = '预览';
								break;
						}
						return status;
					}
					},
					{field: 'CreateTime', title: '创建时间', width: 150},
					{field: 'QrcodeUrl', title: '二维码', width: 80},
					{
						field: 'opt', title: '操作', align: 'center', formatter: function (value, rec, index) {
						var c = '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" ' +
							'onclick="' + _THIS_.selfName + '.editHandler(\'?AID=' + rec.AID + '&Status=' + rec.Status + '\')">';
						c += '<span class="l-btn-left">编辑</span></a>';
						c += '<a href="javascript:void(0);" class="easyui-linkbutton l-btn l-btn-plain" iconcls="icon-edit" onclick="' + _THIS_.selfName + '.adsHandler(\'' + rec.AID + '\')">';
						c += '<span class="l-btn-left">复制链接</span></a>';
						return c;

					}
					}

				]],

				//分页信息
				pagination: true,
				//pagePosition:'both',
				pageList: [20, 50, 100, 150, 200],
				pageSize: 50
			});

		}
	};
</script>
<script type="text/javascript">
	var __CONTROLLER__ = '<?php echo $this->CONTROLLER;?>';
</script>
<script type="text/javascript" src="/static/js/admin/content.js"></script>
<script type="text/javascript">
	column_activityObj = contentCommon(column_activityObj, __CONTROLLER__);
</script>