<!DOCTYPE html>
<html>
<head>
    <title>公告通知</title>
    <meta charset="utf-8">
    <meta name="keywords" content="公告通知" />
    <meta name="description" content="公告通知" />
    <link rel="shortcut icon" href="/static/imgs/web/column/favicon.ico"/>
    <link rel="stylesheet" href="/static/css/column/main.css" />
    <link rel="stylesheet" href="/static/css/column/renzheng.css">
    <link rel="stylesheet" href="/static/css/column/renzheng.css">

	<script src="/static/js/column/jquery-1.10.2.min.js"></script>

</head>
<body>

<div class="header-box">
    <div class="header">
        <h1 class="fl"><img src="/static/imgs/web/column/logo.png" alt="logo" /></h1>
        <div class="header-member fr">
            <a href="">你好，小小大人物</a><span>|</span><a href="#">退出</a>
        </div>
    </div>
</div>

<?php echo $this->layout()->content;?>

<!-- 底部 -->
<div class="footer">
    <p><a href="http://caizhu.com">www.caizhu.com</a> &copy; 2014-2015 All Rights Reserved.</p>
    <p><a href="http://caizhu.com">财猪</a> 版权所有 浙ICP备15011363号-1</p>
</div>


<script>
var _hmt = _hmt || [];
(function() {
    var hm = document.createElement("script");
    hm.src = "//hm.baidu.com/hm.js?8274693fc4b0b74cc746840db3f22f2f";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(hm, s);
})();
</script>
</body>
</html>