<div class="easyui-panel" style="border:0px;">
	<div style="padding:10px 0 10px 30px;align:center;">

		<form id="counsel_order_exceptional_exceptionalClose_form" method="post" enctype="multipart/form-data">
			<table class='form_table'>
				<tr>
					<th width="20%">订单ID：</th>
					<td width="80%"><?php echo $this->except_info['OID'] ?></td>
				</tr>
				<tr>
					<th width="25%">结算百分比：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="commission"
					                       value="0"
					                       data-options="required:true"
					                       size="30"/>%
					</td>
				</tr>
				<tr>
					<th width="20%">关闭原因：</th>
					<td width="80%"><input class="easyui-validatebox" type="text" name="reason"
					                       value=""
					                       data-options="required:true"
					                       size="30"/></td>
				</tr>
				<tr>
					<td colspan='2' class='footbar'>
						<input type="hidden" name="eid" value="<?php echo $this->except_info['EID'] ?>"/>
					</td>
				</tr>
			</table>
		</form>
	</div>

	<div style="text-align:center;padding:5px">
		<a href="javascript:void(0)" class="easyui-linkbutton" id="counsel_order_exceptional_exceptionalClose_form_save">保存</a>
		<a href="javascript:void(0)" class="easyui-linkbutton" id="counsel_order_exceptional_exceptionalClose_form_close">关闭</a>
	</div>

</div>