
<div class="easyui-panel" style="border:0px;">
    <div style="padding:10px 0 10px 30px;align:center;">
    
        <form id="topic_edit_form" method="post" enctype="multipart/form-data">
           <table class='form_table'>                
                <tr>
                    <th width="20%">话题名称：</th>
                    <td width="80%"><input class="easyui-validatebox" type="text" name="TopicName" value = "<?php echo $this->topic['TopicName'];?>" data-options="required:true" size="50" /></td>
                </tr>
                <tr>
                    <th width="20%">匿名状态：</th>
                    <td width="80%">
                        <input type="radio" name="IsAnonymous" <?php if($this->topic['IsAnonymous']==0):?> checked="checked" <?php endif;?> value="0" />实名&nbsp;&nbsp;
                        <input type="radio" name="IsAnonymous" <?php if($this->topic['IsAnonymous']==1):?> checked="checked" <?php endif;?> value="1" />匿名
                    </td>
                </tr>
                 <tr>
                    <th>审核状态：</th>
                    <td>
                        <input name="CheckStatus" <?php if($this->topic['CheckStatus']==0):?> checked="checked" <?php endif;?> type="radio" value="0" />待审核
                        <input name="CheckStatus" <?php if($this->topic['CheckStatus']==1):?> checked="checked" <?php endif;?> type="radio" value="1" />已审核
                        <input name="CheckStatus" <?php if($this->topic['CheckStatus']==2):?> checked="checked" <?php endif;?> type="radio" value="2" />已隐藏
                    </td>
                </tr>
                <tr>
                    <th>选择标签：</th>
                    <td>
                        <?php foreach ($this->focusList as $key => $item):?>
                            <?php if($key && $key%4==0): ?>
                                <br/>
                            <?php endif;?>
                            <input type = "checkbox" name="focusIDArr[]" <?php if(in_array($item['FocusID'], $this->selectFocus)):?> checked = "checked" <?php endif;?> value="<?php echo $item['FocusID'];?>" /><?php echo $item['FocusName']?>&nbsp;&nbsp;&nbsp;&nbsp;
                        <?php endforeach;?>                     
                    </td>    
                </tr>
                <tr>
                    <th>背景图片：</th>
                    <td>
                        <image width="50" height="50" src="<?php echo $this->topic['BackImage'].'?imageView2/0/w/200/h/200' ?>" />
                        <input name = "image"  type="file"/>
                    </td>
                </tr>               
                <tr>
                    <td colspan='2' class='footbar'>
                        <input type="hidden" name="TopicID" value="<?php echo $this->topic['TopicID']?>" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    
    <div style="text-align:center;padding:5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" id="topic_edit_form_save">保存</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" id="topic_edit_form_close">关闭</a>
    </div>
     
</div>